# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)





Paise.create(bandera:"co", nombre:"Colombia")
Paise.create(bandera:"us", nombre:"United States")
Paise.create(bandera:"af", nombre:"Afghanistan")
Paise.create(bandera:"ax", nombre:"Aland Islands")
Paise.create(bandera:"al", nombre:"Albania")
Paise.create(bandera:"dz", nombre:"Algeria")
Paise.create(bandera:"as", nombre:"American Samoa")
Paise.create(bandera:"ad", nombre:"Andorra")
Paise.create(bandera:"ao", nombre:"Angola")
Paise.create(bandera:"ai", nombre:"Anguilla")
Paise.create(bandera:"ag", nombre:"Antigua")
Paise.create(bandera:"ar", nombre:"Argentina")
Paise.create(bandera:"am", nombre:"Armenia")
Paise.create(bandera:"aw", nombre:"Aruba")
Paise.create(bandera:"au", nombre:"Australia")
Paise.create(bandera:"at", nombre:"Austria")
Paise.create(bandera:"az", nombre:"Azerbaijan")
Paise.create(bandera:"bs", nombre:"Bahamas")
Paise.create(bandera:"bh", nombre:"Bahrain")
Paise.create(bandera:"bd", nombre:"Bangladesh")
Paise.create(bandera:"bb", nombre:"Barbados")
Paise.create(bandera:"by", nombre:"Belarus")
Paise.create(bandera:"be", nombre:"Belgium")
Paise.create(bandera:"bz", nombre:"Belize")
Paise.create(bandera:"bj", nombre:"Benin")
Paise.create(bandera:"bm", nombre:"Bermuda")
Paise.create(bandera:"bt", nombre:"Bhutan")
Paise.create(bandera:"bo", nombre:"Bolivia")
Paise.create(bandera:"ba", nombre:"Bosnia")
Paise.create(bandera:"bw", nombre:"Botswana")
Paise.create(bandera:"bv", nombre:"Bouvet Island")
Paise.create(bandera:"br", nombre:"Brazil")
Paise.create(bandera:"vg", nombre:"British Virgin Islands")
Paise.create(bandera:"bn", nombre:"Brunei")
Paise.create(bandera:"bg", nombre:"Bulgaria")
Paise.create(bandera:"bf", nombre:"Burkina Faso")
Paise.create(bandera:"ar", nombre:"Burma")
Paise.create(bandera:"bi", nombre:"Burundi")
Paise.create(bandera:"tc", nombre:"Caicos Islands")
Paise.create(bandera:"kh", nombre:"Cambodia")
Paise.create(bandera:"cm", nombre:"Cameroon")
Paise.create(bandera:"ca", nombre:"Canada")
Paise.create(bandera:"cv", nombre:"Cape Verde")
Paise.create(bandera:"ky", nombre:"Cayman Islands")
Paise.create(bandera:"cf", nombre:"Central African Republic")
Paise.create(bandera:"td", nombre:"Chad")
Paise.create(bandera:"cl", nombre:"Chile")
Paise.create(bandera:"cn", nombre:"China")
Paise.create(bandera:"cx", nombre:"Christmas Island")
Paise.create(bandera:"cc", nombre:"Cocos Islands")
Paise.create(bandera:"km", nombre:"Comoros")
Paise.create(bandera:"cg", nombre:"Congo Brazzaville")
Paise.create(bandera:"cd", nombre:"Congo")
Paise.create(bandera:"ck", nombre:"Cook Islands")
Paise.create(bandera:"cr", nombre:"Costa Rica")
Paise.create(bandera:"ci", nombre:"Cote Divoire")
Paise.create(bandera:"hr", nombre:"Croatia")
Paise.create(bandera:"cu", nombre:"Cuba")
Paise.create(bandera:"cy", nombre:"Cyprus")
Paise.create(bandera:"cz", nombre:"Czech Republic")
Paise.create(bandera:"dk", nombre:"Denmark")
Paise.create(bandera:"dj", nombre:"Djibouti")
Paise.create(bandera:"dm", nombre:"Dominica")
Paise.create(bandera:"do", nombre:"Dominican Republic")
Paise.create(bandera:"ec", nombre:"Ecuador")
Paise.create(bandera:"eg", nombre:"Egypt")
Paise.create(bandera:"sv", nombre:"El Salvador")
Paise.create(bandera:"gb", nombre:"England")
Paise.create(bandera:"gq", nombre:"Equatorial Guinea")
Paise.create(bandera:"er", nombre:"Eritrea")
Paise.create(bandera:"ee", nombre:"Estonia")
Paise.create(bandera:"et", nombre:"Ethiopia")
Paise.create(bandera:"eu", nombre:"European Union")
Paise.create(bandera:"fk", nombre:"Falkland Islands")
Paise.create(bandera:"fo", nombre:"Faroe Islands")
Paise.create(bandera:"fj", nombre:"Fiji")
Paise.create(bandera:"fi", nombre:"Finland")
Paise.create(bandera:"fr", nombre:"France")
Paise.create(bandera:"gf", nombre:"French Guiana")
Paise.create(bandera:"pf", nombre:"French Polynesia")
Paise.create(bandera:"tf", nombre:"French Territories")
Paise.create(bandera:"ga", nombre:"Gabon")
Paise.create(bandera:"gm", nombre:"Gambia")
Paise.create(bandera:"ge", nombre:"Georgia")
Paise.create(bandera:"de", nombre:"Germany")
Paise.create(bandera:"gh", nombre:"Ghana")
Paise.create(bandera:"gi", nombre:"Gibraltar")
Paise.create(bandera:"gr", nombre:"Greece")
Paise.create(bandera:"gl", nombre:"Greenland")
Paise.create(bandera:"gd", nombre:"Grenada")
Paise.create(bandera:"gp", nombre:"Guadeloupe")
Paise.create(bandera:"gu", nombre:"Guam")
Paise.create(bandera:"gt", nombre:"Guatemala")
Paise.create(bandera:"gw", nombre:"Guinea-Bissau")
Paise.create(bandera:"gn", nombre:"Guinea")
Paise.create(bandera:"gy", nombre:"Guyana")
Paise.create(bandera:"ht", nombre:"Haiti")
Paise.create(bandera:"hm", nombre:"Heard Island")
Paise.create(bandera:"hn", nombre:"Honduras")
Paise.create(bandera:"hk", nombre:"Hong Kong")
Paise.create(bandera:"hu", nombre:"Hungary")
Paise.create(bandera:"is", nombre:"Iceland")
Paise.create(bandera:"in", nombre:"India")
Paise.create(bandera:"io", nombre:"Indian Ocean Territory")
Paise.create(bandera:"id", nombre:"Indonesia")
Paise.create(bandera:"ir", nombre:"Iran")
Paise.create(bandera:"iq", nombre:"Iraq")
Paise.create(bandera:"ie", nombre:"Ireland")
Paise.create(bandera:"il", nombre:"Israel")
Paise.create(bandera:"it", nombre:"Italy")
Paise.create(bandera:"jm", nombre:"Jamaica")
Paise.create(bandera:"jp", nombre:"Japan")
Paise.create(bandera:"jo", nombre:"Jordan")
Paise.create(bandera:"kz", nombre:"Kazakhstan")
Paise.create(bandera:"ke", nombre:"Kenya")
Paise.create(bandera:"ki", nombre:"Kiribati")
Paise.create(bandera:"kw", nombre:"Kuwait")
Paise.create(bandera:"kg", nombre:"Kyrgyzstan")
Paise.create(bandera:"la", nombre:"Laos")
Paise.create(bandera:"lv", nombre:"Latvia")
Paise.create(bandera:"lb", nombre:"Lebanon")
Paise.create(bandera:"ls", nombre:"Lesotho")
Paise.create(bandera:"lr", nombre:"Liberia")
Paise.create(bandera:"ly", nombre:"Libya")
Paise.create(bandera:"li", nombre:"Liechtenstein")
Paise.create(bandera:"lt", nombre:"Lithuania")
Paise.create(bandera:"lu", nombre:"Luxembourg")
Paise.create(bandera:"mo", nombre:"Macau")
Paise.create(bandera:"mk", nombre:"Macedonia")
Paise.create(bandera:"mg", nombre:"Madagascar")
Paise.create(bandera:"mw", nombre:"Malawi")
Paise.create(bandera:"my", nombre:"Malaysia")
Paise.create(bandera:"mv", nombre:"Maldives")
Paise.create(bandera:"ml", nombre:"Mali")
Paise.create(bandera:"mt", nombre:"Malta")
Paise.create(bandera:"mh", nombre:"Marshall Islands")
Paise.create(bandera:"mq", nombre:"Martinique")
Paise.create(bandera:"mr", nombre:"Mauritania")
Paise.create(bandera:"mu", nombre:"Mauritius")
Paise.create(bandera:"yt", nombre:"Mayotte")
Paise.create(bandera:"mx", nombre:"Mexico")
Paise.create(bandera:"fm", nombre:"Micronesia")
Paise.create(bandera:"md", nombre:"Moldova")
Paise.create(bandera:"mc", nombre:"Monaco")
Paise.create(bandera:"mn", nombre:"Mongolia")
Paise.create(bandera:"me", nombre:"Montenegro")
Paise.create(bandera:"ms", nombre:"Montserrat")
Paise.create(bandera:"ma", nombre:"Morocco")
Paise.create(bandera:"mz", nombre:"Mozambique")
Paise.create(bandera:"na", nombre:"Namibia")
Paise.create(bandera:"nr", nombre:"Nauru")
Paise.create(bandera:"np", nombre:"Nepal")
Paise.create(bandera:"an", nombre:"Netherlands Antilles")
Paise.create(bandera:"nl", nombre:"Netherlands")
Paise.create(bandera:"nc", nombre:"New Caledonia")
Paise.create(bandera:"pg", nombre:"New Guinea")
Paise.create(bandera:"nz", nombre:"New Zealand")
Paise.create(bandera:"ni", nombre:"Nicaragua")
Paise.create(bandera:"ne", nombre:"Niger")
Paise.create(bandera:"ng", nombre:"Nigeria")
Paise.create(bandera:"nu", nombre:"Niue")
Paise.create(bandera:"nf", nombre:"Norfolk Island")
Paise.create(bandera:"kp", nombre:"North Korea")
Paise.create(bandera:"mp", nombre:"Northern Mariana Islands")
Paise.create(bandera:"no", nombre:"Norway")
Paise.create(bandera:"om", nombre:"Oman")
Paise.create(bandera:"pk", nombre:"Pakistan")
Paise.create(bandera:"pw", nombre:"Palau")
Paise.create(bandera:"ps", nombre:"Palestine")
Paise.create(bandera:"pa", nombre:"Panama")
Paise.create(bandera:"py", nombre:"Paraguay")
Paise.create(bandera:"pe", nombre:"Peru")
Paise.create(bandera:"ph", nombre:"Philippines")
Paise.create(bandera:"pn", nombre:"Pitcairn Islands")
Paise.create(bandera:"pl", nombre:"Poland")
Paise.create(bandera:"pt", nombre:"Portugal")
Paise.create(bandera:"pr", nombre:"Puerto Rico")
Paise.create(bandera:"qa", nombre:"Qatar")
Paise.create(bandera:"re", nombre:"Reunion")
Paise.create(bandera:"ro", nombre:"Romania")
Paise.create(bandera:"ru", nombre:"Russia")
Paise.create(bandera:"rw", nombre:"Rwanda")
Paise.create(bandera:"sh", nombre:"Saint Helena")
Paise.create(bandera:"kn", nombre:"Saint Kitts and Nevis")
Paise.create(bandera:"lc", nombre:"Saint Lucia")
Paise.create(bandera:"pm", nombre:"Saint Pierre")
Paise.create(bandera:"vc", nombre:"Saint Vincent")
Paise.create(bandera:"ws", nombre:"Samoa")
Paise.create(bandera:"sm", nombre:"San Marino")
Paise.create(bandera:"gs", nombre:"Sandwich Islands")
Paise.create(bandera:"st", nombre:"Sao Tome")
Paise.create(bandera:"sa", nombre:"Saudi Arabia")
Paise.create(bandera:"sn", nombre:"Senegal")
Paise.create(bandera:"cs", nombre:"Serbia")
Paise.create(bandera:"rs", nombre:"Serbia")
Paise.create(bandera:"sc", nombre:"Seychelles")
Paise.create(bandera:"sl", nombre:"Sierra Leone")
Paise.create(bandera:"sg", nombre:"Singapore")
Paise.create(bandera:"sk", nombre:"Slovakia")
Paise.create(bandera:"si", nombre:"Slovenia")
Paise.create(bandera:"sb", nombre:"Solomon Islands")
Paise.create(bandera:"so", nombre:"Somalia")
Paise.create(bandera:"za", nombre:"South Africa")
Paise.create(bandera:"kr", nombre:"South Korea")
Paise.create(bandera:"es", nombre:"Spain")
Paise.create(bandera:"lk", nombre:"Sri Lanka")
Paise.create(bandera:"sd", nombre:"Sudan")
Paise.create(bandera:"sr", nombre:"Suriname")
Paise.create(bandera:"sj", nombre:"Svalbard")
Paise.create(bandera:"sz", nombre:"Swaziland")
Paise.create(bandera:"se", nombre:"Sweden")
Paise.create(bandera:"ch", nombre:"Switzerland")
Paise.create(bandera:"sy", nombre:"Syria")
Paise.create(bandera:"tw", nombre:"Taiwan")
Paise.create(bandera:"tj", nombre:"Tajikistan")
Paise.create(bandera:"tz", nombre:"Tanzania")
Paise.create(bandera:"th", nombre:"Thailand")
Paise.create(bandera:"tl", nombre:"Timorleste")
Paise.create(bandera:"tg", nombre:"Togo")
Paise.create(bandera:"tk", nombre:"Tokelau")
Paise.create(bandera:"to", nombre:"Tonga")
Paise.create(bandera:"tt", nombre:"Trinidad")
Paise.create(bandera:"tn", nombre:"Tunisia")
Paise.create(bandera:"tr", nombre:"Turkey")
Paise.create(bandera:"tm", nombre:"Turkmenistan")
Paise.create(bandera:"tv", nombre:"Tuvalu")
Paise.create(bandera:"ug", nombre:"Uganda")
Paise.create(bandera:"ua", nombre:"Ukraine")
Paise.create(bandera:"ae", nombre:"United Arab Emirates")
Paise.create(bandera:"uy", nombre:"Uruguay")
Paise.create(bandera:"um", nombre:"Us Minor Islands")
Paise.create(bandera:"vi", nombre:"Us Virgin Islands")
Paise.create(bandera:"uz", nombre:"Uzbekistan")
Paise.create(bandera:"vu", nombre:"Vanuatu")
Paise.create(bandera:"va", nombre:"Vatican City")
Paise.create(bandera:"ve", nombre:"Venezuela")
Paise.create(bandera:"vn", nombre:"Vietnam")
Paise.create(bandera:"wf", nombre:"Wallis and Futuna")
Paise.create(bandera:"eh", nombre:"Western Sahara")
Paise.create(bandera:"ye", nombre:"Yemen")
Paise.create(bandera:"zm", nombre:"Zambia")
Paise.create(bandera:"zw", nombre:"Zimbabwe")


TipoDeSexo.create( nombre: "Masculino")
TipoDeSexo.create( nombre: "Femenino")

TipoEstadoCivil.create(nombre:"Soltero")
TipoEstadoCivil.create(nombre:"Casado")
TipoEstadoCivil.create(nombre:"Viudo")
TipoEstadoCivil.create(nombre:"Separado")

TipoDocumento.create(nombre: "C.C.")
TipoDocumento.create(nombre: "C.E.")


Religion.create(nombre: "Cristiano")
Religion.create(nombre: "Judio")
Religion.create(nombre: "Evangelico")
Religion.create(nombre: "Catolico")
Religion.create(nombre: "Otro")


Tenenciavivienda.create(nombre: "Propia")
Tenenciavivienda.create(nombre: "Alquilada")
Tenenciavivienda.create(nombre: "Familiar")
Tenenciavivienda.create(nombre: "Albergue")

Tipocontacto.create(nombre:"Casa")
Tipocontacto.create(nombre:"Movil")
Tipocontacto.create(nombre:"Trabajo")

Ubicacionvivienda.create(nombre:"Area Urbana")
h = Ubicacionvivienda.create(nombre:"Area Rural")

Detalleubicacion.create(nombre:"Disperso", ubicacionvivienda:h)
Detalleubicacion.create(nombre:"Centro Poblado", ubicacionvivienda:h)


Tipoestudio.create(nombre:"Sin escolaridad")
Tipoestudio.create(nombre:"Primaria Incompleta")
Tipoestudio.create(nombre:"Primaria Completa")
Tipoestudio.create(nombre:"Secundaria Incompleta")
Tipoestudio.create(nombre:"Secundaria Completa")
Tipoestudio.create(nombre:"Tecnico Incompleta")
Tipoestudio.create(nombre:"Tecnico Completa")
Tipoestudio.create(nombre:"Tecnologo Incompleta")
Tipoestudio.create(nombre:"Tecnologo Completa")
Tipoestudio.create(nombre:"Pregrado Incompleta")
Tipoestudio.create(nombre:"Pregrado Completa")
Tipoestudio.create(nombre:"Especializacion Incompleta")
Tipoestudio.create(nombre:"Especializacion Completa")
Tipoestudio.create(nombre:"Maestria Incompleta")
Tipoestudio.create(nombre:"Maestria Completa")
Tipoestudio.create(nombre:"Doctorado Incompleta")
Tipoestudio.create(nombre:"Doctorado Completa")


Jornadaestudio.create(nombre:"Distancia")
Jornadaestudio.create(nombre:"Presencial")
Jornadaestudio.create(nombre:"Semipresencial")
Jornadaestudio.create(nombre:"Virtual")

Aptitude.create(id: 1,nombre:"Responsabilidad")
Aptitude.create(id: 2,nombre:"Liderazgo")

PruebasCompetencia.create(id: 1,aptitudes_id: 1, nombre:"Prueba de Responsabilidad")
PruebasCompetencia.create(id: 2,aptitudes_id: 2,nombre: "Prueba de Liderazgo")

Pregunta.create(id:1,pruebas_competencia_id: 1,nombre:"PARTIENDO DE EXPERIENCIAS PASADAS, USTED SE CARACTERIZA POR:")

OpcionesRespuestum.create(pregunta_id:1,valor: 1,nombre:"Cumple con las políticas organizacionales en materia de responsabilidad social, solo cuando se le solicita")
OpcionesRespuestum.create(pregunta_id:1,valor: 2,nombre:"se identifica con las políticas sociales en materias de responsabilidad social")
OpcionesRespuestum.create(pregunta_id:1,valor: 3,nombre:"Promueve las políticas organizacionales en materia de responsabilidad social.")
OpcionesRespuestum.create(pregunta_id:1,valor: 4,nombre:"Fija políticas organizacionales en materia de responsabilidad social, con visión de largo plazo.")
OpcionesRespuestum.create(pregunta_id:1,valor: 5,nombre:"Se identifica con las políticas organizacionales en materia de responsabilidad social, y motiva a los colaboradores y/o pares de su área a actuar de la misma manera.")

Pregunta.create(id:2,pruebas_competencia_id: 1,nombre:"LO QUE HACE DIFERENTES SUS ACCIONES A LA DEL RESTO DE SUS COMPAÑEROS ES PORQUE:")

OpcionesRespuestum.create(pregunta_id:2,valor: 1,nombre:"No propone acciones orientadas a colaborar con la sociedad")
OpcionesRespuestum.create(pregunta_id:2,valor: 2,nombre:"Lleva a cabo acciones orientadas a colaborar con la sociedad en todo aquello que guarde relación con sus propias tareas o responsabilidades.")
OpcionesRespuestum.create(pregunta_id:2,valor: 3,nombre:"Propone acciones orientadas a colaborar con la sociedad en las áreas donde ésta presenta mayores carencias.")
OpcionesRespuestum.create(pregunta_id:2,valor: 4,nombre:"Diseña, propone y lleva a cabo junto con su área de trabajo, propuestas orientadas a contribuir y colaborar con la sociedad en las áreas donde esta presenta mayores carencias")
OpcionesRespuestum.create(pregunta_id:2,valor: 5,nombre:"Diseña, propone y luego lleva a cabo propuestas orientadas a contribuir y colaborar con la sociedad en las áreas en las cuales esta presenta mayores carencias, y por ende, mayor necesidad de ayuda y colaboración")


Pregunta.create(id:3,pruebas_competencia_id: 1,nombre:"FRENTE A SITUACIONES QUE NO CORRESPONDEN A SU ACTUAR COTIDIANO USTED:")

OpcionesRespuestum.create(pregunta_id:3,valor: 1,nombre:"Le cuesta comprender otras culturas y adaptarse a ellas, por lo que no logra realizar un aporte significativo a las políticas organizacionales en materia de responsabilidad social.")
OpcionesRespuestum.create(pregunta_id:3,valor: 2,nombre:"Comprende rápidamente otras culturas")
OpcionesRespuestum.create(pregunta_id:3,valor: 3,nombre:"Comprende otras culturas y utiliza dicha comprensión en beneficio de las políticas organizacionales en materia de responsabilidad social.")
OpcionesRespuestum.create(pregunta_id:3,valor: 4,nombre:"Comprende otras culturas, sus maneras de pensar y comportarse y utiliza dicha comprensión en beneficio de las políticas organizacionales en materia de responsabilidad social")
OpcionesRespuestum.create(pregunta_id:3,valor: 5,nombre:"Comprende rápidamente otras culturas, sus maneras de pensar y comportarse en las diferentes formas de hacer las cosas, y utiliza dicha comprensión en beneficio de las políticas organizacionales en materia de responsabilidad social.")

Pregunta.create(id:4,pruebas_competencia_id: 1,nombre:"¿SE HA VISTO EXPUESTO A ALGUNA DE LAS SIGUIENTES SITUACIONES?")


OpcionesRespuestum.create(pregunta_id:4,valor: 1,nombre:"No se involucra en la implementación de los planes de asistencia y ayuda social que la organización realiza, por considerar que sus responsabilidades y obligaciones laborales requiere de su dedicación absoluta o porque piensa que hacerlo no corresponde a su rol")
OpcionesRespuestum.create(pregunta_id:4,valor: 2,nombre:"Promociona de manera formal e informal, los programas de asistencia con los que cuenta la organización, a fin de que lleguen quienes los necesitan")
OpcionesRespuestum.create(pregunta_id:4,valor: 3,nombre:"Desarrolla y participa activamente en la implementación de planes orientados a fomentar el bien común")
OpcionesRespuestum.create(pregunta_id:4,valor: 4,nombre:"Colabora en la implementación de los planes de asistencia y ayuda social que lleva adelante la organización.")
OpcionesRespuestum.create(pregunta_id:4,valor: 5,nombre:"Participa e interviene en el desarrollo y ejecución de los planes de asistencia que instrumenta su organización, y fomenta igual actitud entre sus colaboradores.")

Pregunta.create(id:5,pruebas_competencia_id: 1,nombre:"DENTRO DE LOS EQUIPOS DE TRABAJO A LOS QUE HA HECHO PARTE, USTED SE DISTINGUE POR:")
OpcionesRespuestum.create(pregunta_id:5,valor: 1,nombre:"No comprende el porqué de las políticas organizacionales en materia de responsabilidad social; considera que la asistencia y ayuda en los temas sociales es responsabilidad exclusiva de los organismos del sector público")
OpcionesRespuestum.create(pregunta_id:5,valor: 2,nombre:"Es un referente para sus compañeros en materia de responsabilidad social")
OpcionesRespuestum.create(pregunta_id:5,valor: 3,nombre:"Es un refrene para sus colaboradores y en el ámbito del área en dónde se desempeña en materia de responsabilidad social")
OpcionesRespuestum.create(pregunta_id:5,valor: 4,nombre:"Es un referente de su área y en el ámbito de la organización en materia de responsabilidad social.")
OpcionesRespuestum.create(pregunta_id:5,valor: 5,nombre:"Es un referente en la organización y en el mercado donde actúa en materia de responsabilidad social.")













Pregunta.create(id:6,pruebas_competencia_id: 2,nombre:"¿HA SIDO RECONOCIDO POR ALGUNOS DE LOS SIGUIENTES COMPORTAMIENTOS?")

OpcionesRespuestum.create(pregunta_id:6,valor: 1,nombre:"no logra asegurar una adecuada conducción de personas ni desarrollar su talento")
OpcionesRespuestum.create(pregunta_id:6,valor: 2,nombre:"Asegura una adecuada conducción de personas y el desarrollo de su talento")
OpcionesRespuestum.create(pregunta_id:6,valor: 3,nombre:"Busca siempre asegurar una adecuada conducción de personas y el desarrollo de su talento y propone nuevas estrategias para ello cuando lo considera oportuno")
OpcionesRespuestum.create(pregunta_id:6,valor: 4,nombre:"Propone y diseña proceso y cursos de acción y métodos de trabajo con el propósito de asegurar una adecuada conducción de personas y desarrollar su talento.")
OpcionesRespuestum.create(pregunta_id:6,valor: 5,nombre:"Diseña estrategias, procesos, cursos de acción y métodos de trabajo con el propósito de asegurar una exitosa conducción de personas y desarrollar su talento.")

Pregunta.create(id:7,pruebas_competencia_id: 2,nombre:"EN SU DIARIO VIVIR, USTED SUELE:")
OpcionesRespuestum.create(pregunta_id:7,valor: 1,nombre:"No es eficaz para obtener el compromiso y el respalda de sus superiores a fin de enfrentar los desafíos del equipo que integra los equipos a su cargo.")
OpcionesRespuestum.create(pregunta_id:7,valor: 2,nombre:"tiene el compromiso y respaldo de sus superiores para el logro de los desafíos del equipo que integra")
OpcionesRespuestum.create(pregunta_id:7,valor: 3,nombre:"Propone cursos de acción con el fin de lograr el compromiso y respaldo de sus superiores para enfrentar los desafíos a su cargo.")
OpcionesRespuestum.create(pregunta_id:7,valor: 4,nombre:"Delinea estrategias y cursos de acción con el fin de lograr el compromiso y el respaldo de las distintas áreas de la organización para alcanzar la estrategia.")
OpcionesRespuestum.create(pregunta_id:7,valor: 5,nombre:"Propone y diseña procesos y cursos de acción con el fin de lograr el compromiso y respaldo de sus superiores para enfrentar los desafíos propuestas para su área.")

Pregunta.create(id:8,pruebas_competencia_id: 2,nombre:"DENTRO DE LOS EQUIPOS DE TRABAJO A LOS QUE HA PERTENECIDO USTED SE HA DISTIGUIDO PORQUE:")
OpcionesRespuestum.create(pregunta_id:8,valor: 1,nombre:"genera un clima organizacional tenso")
OpcionesRespuestum.create(pregunta_id:8,valor: 2,nombre:"Propicia un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:8,valor: 3,nombre:"Contribuye a mantener un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:8,valor: 4,nombre:"Genera y mantiene un modo activo, un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:8,valor: 5,nombre:"promueve y sostiene un clima organizacional armónico y desafiante ")

Pregunta.create(id:9,pruebas_competencia_id: 2,nombre:"LA GENTE QUE LO CONOCE PODRÍA DECIR DE USTED QUE:")
OpcionesRespuestum.create(pregunta_id:9,valor: 1,nombre:"No es vista por su entorno organizacional como un ejemplo a seguir por su capacidad de liderar y lograr un desarrollar de sus colaboradores ")
OpcionesRespuestum.create(pregunta_id:9,valor: 2,nombre:"Propicia un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:9,valor: 3,nombre:"Contribuye a mantener un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:9,valor: 4,nombre:"Genera y mantiene un modo activo, un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:9,valor: 5,nombre:"promueve y sostiene un clima organizacional armónico y desafiante ")

Pregunta.create(id:10,pruebas_competencia_id: 2,nombre:"¿CUAL DE LOS SIGUIENTES POSTULADOS LO DEFINEN DE MEJOR MANERA?")
OpcionesRespuestum.create(pregunta_id:10,valor: 1,nombre:"Carece de visión y proyección a futuro para la conducción y desarrollo de personas ")
OpcionesRespuestum.create(pregunta_id:10,valor: 2,nombre:"Muestra visión y proyección, en el corto plazo, para la conducción y desarrollo de personas")
OpcionesRespuestum.create(pregunta_id:10,valor: 3,nombre:"Considera la necesidad de pensar a futuro en la conducción y desarrollo de personas ")
OpcionesRespuestum.create(pregunta_id:10,valor: 4,nombre:"su desempeño en la conducción y desarrollo de personas transluce visión y proyección en el mediano plazo")
OpcionesRespuestum.create(pregunta_id:10,valor: 5,nombre:"Evidencia visión y proyección de largo plazo en la conducción y desarrollo de personas")



Departamento.create(id: 0 , nombre: "Amazonas")
Departamento.create(id: 1 , nombre: "Antioquia")
Departamento.create(id: 2 , nombre: "Arauca")
Departamento.create(id: 3 , nombre: "Atlántico")
Departamento.create(id: 4 , nombre: "Bolívar")
Departamento.create(id: 5 , nombre: "Boyacá")
Departamento.create(id: 6 , nombre: "Caldas")
Departamento.create(id: 7 , nombre: "Caquetá")
Departamento.create(id: 8 , nombre: "Casanare")
Departamento.create(id: 9 , nombre: "Cauca")
Departamento.create(id: 10 , nombre: "Cesar")
Departamento.create(id: 11 , nombre: "Chocó")
Departamento.create(id: 12 , nombre: "Cundinamarca")
Departamento.create(id: 13 , nombre: "Córdoba")
Departamento.create(id: 14 , nombre: "Guainía")
Departamento.create(id: 15 , nombre: "Guaviare")
Departamento.create(id: 16 , nombre: "Huila")
Departamento.create(id: 17 , nombre: "La Guajira")
Departamento.create(id: 18 , nombre: "Magdalena")
Departamento.create(id: 19 , nombre: "Meta")
Departamento.create(id: 20 , nombre: "Nariño")
Departamento.create(id: 21 , nombre: "Norte de Santander")
Departamento.create(id: 22 , nombre: "Putumayo")
Departamento.create(id: 23 , nombre: "Quindío")
Departamento.create(id: 24 , nombre: "Risaralda")
Departamento.create(id: 25 , nombre: "San Andrés y Providencia")
Departamento.create(id: 26 , nombre: "Santander")
Departamento.create(id: 27 , nombre: "Sucre")
Departamento.create(id: 28 , nombre: "Tolima")
Departamento.create(id: 29 , nombre: "Valle del Cauca")
Departamento.create(id: 30 , nombre: "Vaupés")
Departamento.create(id: 31 , nombre: "Vichada")

Municipio.create!(nombre: " Leticia ", departamento_id: 0 )
Municipio.create(nombre: " Puerto Nariño ", departamento_id: 0 )

Municipio.create(nombre: " Abejorral ", departamento_id: 1 )
Municipio.create(nombre: " Abriaquí ", departamento_id: 1 )
Municipio.create(nombre: " Alejandría ", departamento_id: 1 )
Municipio.create(nombre: " Amagá ", departamento_id: 1 )
Municipio.create(nombre: " Amalfi ", departamento_id: 1 )
Municipio.create(nombre: " Andes ", departamento_id: 1 )
Municipio.create(nombre: " Angelópolis ", departamento_id: 1 )
Municipio.create(nombre: " Angostura ", departamento_id: 1 )
Municipio.create(nombre: " Anorí ", departamento_id: 1 )
Municipio.create(nombre: " Anzá ", departamento_id: 1 )
Municipio.create(nombre: " Apartadó ", departamento_id: 1 )
Municipio.create(nombre: " Arboletes ", departamento_id: 1 )
Municipio.create(nombre: " Argelia ", departamento_id: 1 )
Municipio.create(nombre: " Armenia ", departamento_id: 1 )
Municipio.create(nombre: " Barbosa ", departamento_id: 1 )
Municipio.create(nombre: " Bello ", departamento_id: 1 )
Municipio.create(nombre: " Belmira ", departamento_id: 1 )
Municipio.create(nombre: " Betania ", departamento_id: 1 )
Municipio.create(nombre: " Betulia ", departamento_id: 1 )
Municipio.create(nombre: " Briceño ", departamento_id: 1 )
Municipio.create(nombre: " Buriticá ", departamento_id: 1 )
Municipio.create(nombre: " Cáceres ", departamento_id: 1 )
Municipio.create(nombre: " Caicedo ", departamento_id: 1 )
Municipio.create(nombre: " Caldas ", departamento_id: 1 )
Municipio.create(nombre: " Campamento ", departamento_id: 1 )
Municipio.create(nombre: " Cañasgordas ", departamento_id: 1 )
Municipio.create(nombre: " Caracolí ", departamento_id: 1 )
Municipio.create(nombre: " Caramanta ", departamento_id: 1 )
Municipio.create(nombre: " Carepa ", departamento_id: 1 )
Municipio.create(nombre: " Carolina del Príncipe ", departamento_id: 1 )
Municipio.create(nombre: " Caucasia ", departamento_id: 1 )
Municipio.create(nombre: " Chigorodó ", departamento_id: 1 )
Municipio.create(nombre: " Cisneros ", departamento_id: 1 )
Municipio.create(nombre: " Ciudad Bolívar ", departamento_id: 1 )
Municipio.create(nombre: " Cocorná ", departamento_id: 1 )
Municipio.create(nombre: " Concepción ", departamento_id: 1 )
Municipio.create(nombre: " Concordia ", departamento_id: 1 )
Municipio.create(nombre: " Copacabana ", departamento_id: 1 )
Municipio.create(nombre: " Dabeiba ", departamento_id: 1 )
Municipio.create(nombre: " Donmatías ", departamento_id: 1 )
Municipio.create(nombre: " Ebéjico ", departamento_id: 1 )
Municipio.create(nombre: " El Bagre ", departamento_id: 1 )
Municipio.create(nombre: " El Carmen de Viboral ", departamento_id: 1 )
Municipio.create(nombre: " El Peñol ", departamento_id: 1 )
Municipio.create(nombre: " El Retiro ", departamento_id: 1 )
Municipio.create(nombre: " El Santuario ", departamento_id: 1 )
Municipio.create(nombre: " Entrerríos ", departamento_id: 1 )
Municipio.create(nombre: " Envigado ", departamento_id: 1 )
Municipio.create(nombre: " Fredonia ", departamento_id: 1 )
Municipio.create(nombre: " Frontino ", departamento_id: 1 )
Municipio.create(nombre: " Giraldo ", departamento_id: 1 )
Municipio.create(nombre: " Girardota ", departamento_id: 1 )
Municipio.create(nombre: " Gómez Plata ", departamento_id: 1 )
Municipio.create(nombre: " Granada ", departamento_id: 1 )
Municipio.create(nombre: " Guadalupe ", departamento_id: 1 )
Municipio.create(nombre: " Guarne ", departamento_id: 1 )
Municipio.create(nombre: " Guatapé ", departamento_id: 1 )
Municipio.create(nombre: " Heliconia ", departamento_id: 1 )
Municipio.create(nombre: " Hispania ", departamento_id: 1 )
Municipio.create(nombre: " Itagüí ", departamento_id: 1 )
Municipio.create(nombre: " Ituango ", departamento_id: 1 )
Municipio.create(nombre: " Jardín ", departamento_id: 1 )
Municipio.create(nombre: " Jericó ", departamento_id: 1 )
Municipio.create(nombre: " La Ceja ", departamento_id: 1 )
Municipio.create(nombre: " La Estrella ", departamento_id: 1 )
Municipio.create(nombre: " La Pintada ", departamento_id: 1 )
Municipio.create(nombre: " La Unión ", departamento_id: 1 )
Municipio.create(nombre: " Liborina ", departamento_id: 1 )
Municipio.create(nombre: " Maceo ", departamento_id: 1 )
Municipio.create(nombre: " Marinilla ", departamento_id: 1 )
Municipio.create(nombre: " Medellín ", departamento_id: 1 )
Municipio.create(nombre: " Montebello ", departamento_id: 1 )
Municipio.create(nombre: " Murindó ", departamento_id: 1 )
Municipio.create(nombre: " Mutatá ", departamento_id: 1 )
Municipio.create(nombre: " Nariño ", departamento_id: 1 )
Municipio.create(nombre: " Nechí ", departamento_id: 1 )
Municipio.create(nombre: " Necoclí ", departamento_id: 1 )
Municipio.create(nombre: " Olaya ", departamento_id: 1 )
Municipio.create(nombre: " Peque ", departamento_id: 1 )
Municipio.create(nombre: " Pueblorrico ", departamento_id: 1 )
Municipio.create(nombre: " Puerto Berrío ", departamento_id: 1 )
Municipio.create(nombre: " Puerto Nare ", departamento_id: 1 )
Municipio.create(nombre: " Puerto Triunfo ", departamento_id: 1 )
Municipio.create(nombre: " Remedios ", departamento_id: 1 )
Municipio.create(nombre: " Rionegro ", departamento_id: 1 )
Municipio.create(nombre: " Sabanalarga ", departamento_id: 1 )
Municipio.create(nombre: " Sabaneta ", departamento_id: 1 )
Municipio.create(nombre: " Salgar ", departamento_id: 1 )
Municipio.create(nombre: " San Andrés de Cuerquia ", departamento_id: 1 )
Municipio.create(nombre: " San Carlos ", departamento_id: 1 )
Municipio.create(nombre: " San Francisco ", departamento_id: 1 )
Municipio.create(nombre: " San Jerónimo ", departamento_id: 1 )
Municipio.create(nombre: " San José de la Montaña ", departamento_id: 1 )
Municipio.create(nombre: " San Juan de Urabá ", departamento_id: 1 )
Municipio.create(nombre: " San Luis ", departamento_id: 1 )
Municipio.create(nombre: " San Pedro de Urabá ", departamento_id: 1 )
Municipio.create(nombre: " San Pedro de los Milagros ", departamento_id: 1 )
Municipio.create(nombre: " San Rafael ", departamento_id: 1 )
Municipio.create(nombre: " San Roque ", departamento_id: 1 )
Municipio.create(nombre: " San Vicente ", departamento_id: 1 )
Municipio.create(nombre: " Santa Bárbara ", departamento_id: 1 )
Municipio.create(nombre: " Santa Fe de Antioquia ", departamento_id: 1 )
Municipio.create(nombre: " Santa Rosa de Osos ", departamento_id: 1 )
Municipio.create(nombre: " Santo Domingo ", departamento_id: 1 )
Municipio.create(nombre: " Segovia ", departamento_id: 1 )
Municipio.create(nombre: " Sonsón ", departamento_id: 1 )
Municipio.create(nombre: " Sopetrán ", departamento_id: 1 )
Municipio.create(nombre: " Támesis ", departamento_id: 1 )
Municipio.create(nombre: " Tarazá ", departamento_id: 1 )
Municipio.create(nombre: " Tarso ", departamento_id: 1 )
Municipio.create(nombre: " Titiribí ", departamento_id: 1 )
Municipio.create(nombre: " Toledo ", departamento_id: 1 )
Municipio.create(nombre: " Turbo ", departamento_id: 1 )
Municipio.create(nombre: " Uramita ", departamento_id: 1 )
Municipio.create(nombre: " Urrao ", departamento_id: 1 )
Municipio.create(nombre: " Valdivia ", departamento_id: 1 )
Municipio.create(nombre: " Valparaíso ", departamento_id: 1 )
Municipio.create(nombre: " Vegachí ", departamento_id: 1 )
Municipio.create(nombre: " Venecia ", departamento_id: 1 )
Municipio.create(nombre: " Vigía del Fuerte ", departamento_id: 1 )
Municipio.create(nombre: " Yalí ", departamento_id: 1 )
Municipio.create(nombre: " Yarumal ", departamento_id: 1 )
Municipio.create(nombre: " Yolombó ", departamento_id: 1 )
Municipio.create(nombre: " Yondó ", departamento_id: 1 )
Municipio.create(nombre: " Zaragoza ", departamento_id: 1 )

Municipio.create(nombre: " Arauca ", departamento_id: 2 )
Municipio.create(nombre: " Arauquita ", departamento_id: 2 )
Municipio.create(nombre: " Cravo Norte ", departamento_id: 2 )
Municipio.create(nombre: " Fortul ", departamento_id: 2 )
Municipio.create(nombre: " Puerto Rondón ", departamento_id: 2 )
Municipio.create(nombre: " Saravena ", departamento_id: 2 )
Municipio.create(nombre: " Tame ", departamento_id: 2 )

Municipio.create(nombre: " Baranoa ", departamento_id: 3 )
Municipio.create(nombre: " Barranquilla ", departamento_id: 3 )
Municipio.create(nombre: " Campo de la Cruz ", departamento_id: 3 )
Municipio.create(nombre: " Candelaria ", departamento_id: 3 )
Municipio.create(nombre: " Galapa ", departamento_id: 3 )
Municipio.create(nombre: " Juan de Acosta ", departamento_id: 3 )
Municipio.create(nombre: " Luruaco ", departamento_id: 3 )
Municipio.create(nombre: " Malambo ", departamento_id: 3 )
Municipio.create(nombre: " Manatí ", departamento_id: 3 )
Municipio.create(nombre: " Palmar de Varela ", departamento_id: 3 )
Municipio.create(nombre: " Piojó ", departamento_id: 3 )
Municipio.create(nombre: " Polonuevo ", departamento_id: 3 )
Municipio.create(nombre: " Ponedera ", departamento_id: 3 )
Municipio.create(nombre: " Puerto Colombia ", departamento_id: 3 )
Municipio.create(nombre: " Repelón ", departamento_id: 3 )
Municipio.create(nombre: " Sabanagrande ", departamento_id: 3 )
Municipio.create(nombre: " Sabanalarga ", departamento_id: 3 )
Municipio.create(nombre: " Santa Lucía ", departamento_id: 3 )
Municipio.create(nombre: " Santo Tomás ", departamento_id: 3 )
Municipio.create(nombre: " Soledad ", departamento_id: 3 )
Municipio.create(nombre: " Suán ", departamento_id: 3 )
Municipio.create(nombre: " Tubará ", departamento_id: 3 )
Municipio.create(nombre: " Usiacurí ", departamento_id: 3 )

Municipio.create(nombre: " Achí ", departamento_id: 4 )
Municipio.create(nombre: " Altos del Rosario ", departamento_id: 4 )
Municipio.create(nombre: " Arenal ", departamento_id: 4 )
Municipio.create(nombre: " Arjona ", departamento_id: 4 )
Municipio.create(nombre: " Arroyohondo ", departamento_id: 4 )
Municipio.create(nombre: " Barranco de Loba ", departamento_id: 4 )
Municipio.create(nombre: " Brazuelo de Papayal ", departamento_id: 4 )
Municipio.create(nombre: " Calamar ", departamento_id: 4 )
Municipio.create(nombre: " Cantagallo ", departamento_id: 4 )
Municipio.create(nombre: " Cartagena de Indias ", departamento_id: 4 )
Municipio.create(nombre: " Cicuco ", departamento_id: 4 )
Municipio.create(nombre: " Clemencia ", departamento_id: 4 )
Municipio.create(nombre: " Córdoba ", departamento_id: 4 )
Municipio.create(nombre: " El Carmen de Bolívar ", departamento_id: 4 )
Municipio.create(nombre: " El Guamo ", departamento_id: 4 )
Municipio.create(nombre: " El Peñón ", departamento_id: 4 )
Municipio.create(nombre: " Hatillo de Loba ", departamento_id: 4 )
Municipio.create(nombre: " Magangué ", departamento_id: 4 )
Municipio.create(nombre: " Mahates ", departamento_id: 4 )
Municipio.create(nombre: " Margarita ", departamento_id: 4 )
Municipio.create(nombre: " María la Baja ", departamento_id: 4 )
Municipio.create(nombre: " Mompós ", departamento_id: 4 )
Municipio.create(nombre: " Montecristo ", departamento_id: 4 )
Municipio.create(nombre: " Morales ", departamento_id: 4 )
Municipio.create(nombre: " Norosí ", departamento_id: 4 )
Municipio.create(nombre: " Pinillos ", departamento_id: 4 )
Municipio.create(nombre: " Regidor ", departamento_id: 4 )
Municipio.create(nombre: " Río Viejo ", departamento_id: 4 )
Municipio.create(nombre: " San Cristóbal ", departamento_id: 4 )
Municipio.create(nombre: " San Estanislao ", departamento_id: 4 )
Municipio.create(nombre: " San Fernando ", departamento_id: 4 )
Municipio.create(nombre: " San Jacinto del Cauca ", departamento_id: 4 )
Municipio.create(nombre: " San Jacinto ", departamento_id: 4 )
Municipio.create(nombre: " San Juan Nepomuceno ", departamento_id: 4 )
Municipio.create(nombre: " San Martín de Loba ", departamento_id: 4 )
Municipio.create(nombre: " San Pablo ", departamento_id: 4 )
Municipio.create(nombre: " Santa Catalina ", departamento_id: 4 )
Municipio.create(nombre: " Santa Rosa ", departamento_id: 4 )
Municipio.create(nombre: " Santa Rosa del Sur ", departamento_id: 4 )
Municipio.create(nombre: " Simití ", departamento_id: 4 )
Municipio.create(nombre: " Soplaviento ", departamento_id: 4 )
Municipio.create(nombre: " Talaigua Nuevo ", departamento_id: 4 )
Municipio.create(nombre: " Tiquisio ", departamento_id: 4 )
Municipio.create(nombre: " Turbaco ", departamento_id: 4 )
Municipio.create(nombre: " Turbaná ", departamento_id: 4 )
Municipio.create(nombre: " Villanueva ", departamento_id: 4 )
Municipio.create(nombre: " Zambrano ", departamento_id: 4 )

Municipio.create(nombre: " Almeida ", departamento_id: 5 )
Municipio.create(nombre: " Aquitania ", departamento_id: 5 )
Municipio.create(nombre: " Arcabuco ", departamento_id: 5 )
Municipio.create(nombre: " Belén ", departamento_id: 5 )
Municipio.create(nombre: " Berbeo ", departamento_id: 5 )
Municipio.create(nombre: " Betéitiva ", departamento_id: 5 )
Municipio.create(nombre: " Boavita ", departamento_id: 5 )
Municipio.create(nombre: " Boyacá ", departamento_id: 5 )
Municipio.create(nombre: " Briceño ", departamento_id: 5 )
Municipio.create(nombre: " Buenavista ", departamento_id: 5 )
Municipio.create(nombre: " Busbanzá ", departamento_id: 5 )
Municipio.create(nombre: " Caldas ", departamento_id: 5 )
Municipio.create(nombre: " Campohermoso ", departamento_id: 5 )
Municipio.create(nombre: " Cerinza ", departamento_id: 5 )
Municipio.create(nombre: " Chinavita ", departamento_id: 5 )
Municipio.create(nombre: " Chiquinquirá ", departamento_id: 5 )
Municipio.create(nombre: " Chíquiza ", departamento_id: 5 )
Municipio.create(nombre: " Chiscas ", departamento_id: 5 )
Municipio.create(nombre: " Chita ", departamento_id: 5 )
Municipio.create(nombre: " Chitaraque ", departamento_id: 5 )
Municipio.create(nombre: " Chivatá ", departamento_id: 5 )
Municipio.create(nombre: " Chivor ", departamento_id: 5 )
Municipio.create(nombre: " Ciénega ", departamento_id: 5 )
Municipio.create(nombre: " Cómbita ", departamento_id: 5 )
Municipio.create(nombre: " Coper ", departamento_id: 5 )
Municipio.create(nombre: " Corrales ", departamento_id: 5 )
Municipio.create(nombre: " Covarachía ", departamento_id: 5 )
Municipio.create(nombre: " Cubará ", departamento_id: 5 )
Municipio.create(nombre: " Cucaita ", departamento_id: 5 )
Municipio.create(nombre: " Cuítiva ", departamento_id: 5 )
Municipio.create(nombre: " Duitama ", departamento_id: 5 )
Municipio.create(nombre: " El Cocuy ", departamento_id: 5 )
Municipio.create(nombre: " El Espino ", departamento_id: 5 )
Municipio.create(nombre: " Firavitoba ", departamento_id: 5 )
Municipio.create(nombre: " Floresta ", departamento_id: 5 )
Municipio.create(nombre: " Gachantivá ", departamento_id: 5 )
Municipio.create(nombre: " Gámeza ", departamento_id: 5 )
Municipio.create(nombre: " Garagoa ", departamento_id: 5 )
Municipio.create(nombre: " Guacamayas ", departamento_id: 5 )
Municipio.create(nombre: " Guateque ", departamento_id: 5 )
Municipio.create(nombre: " Guayatá ", departamento_id: 5 )
Municipio.create(nombre: " Güicán ", departamento_id: 5 )
Municipio.create(nombre: " Iza ", departamento_id: 5 )
Municipio.create(nombre: " Jenesano ", departamento_id: 5 )
Municipio.create(nombre: " Jericó ", departamento_id: 5 )
Municipio.create(nombre: " La Capilla ", departamento_id: 5 )
Municipio.create(nombre: " La Uvita ", departamento_id: 5 )
Municipio.create(nombre: " La Victoria ", departamento_id: 5 )
Municipio.create(nombre: " Labranzagrande ", departamento_id: 5 )
Municipio.create(nombre: " Macanal ", departamento_id: 5 )
Municipio.create(nombre: " Maripí ", departamento_id: 5 )
Municipio.create(nombre: " Miraflores ", departamento_id: 5 )
Municipio.create(nombre: " Mongua ", departamento_id: 5 )
Municipio.create(nombre: " Monguí ", departamento_id: 5 )
Municipio.create(nombre: " Moniquirá ", departamento_id: 5 )
Municipio.create(nombre: " Motavita ", departamento_id: 5 )
Municipio.create(nombre: " Muzo ", departamento_id: 5 )
Municipio.create(nombre: " Nobsa ", departamento_id: 5 )
Municipio.create(nombre: " Nuevo Colón ", departamento_id: 5 )
Municipio.create(nombre: " Oicatá ", departamento_id: 5 )
Municipio.create(nombre: " Otanche ", departamento_id: 5 )
Municipio.create(nombre: " Pachavita ", departamento_id: 5 )
Municipio.create(nombre: " Páez ", departamento_id: 5 )
Municipio.create(nombre: " Paipa ", departamento_id: 5 )
Municipio.create(nombre: " Pajarito ", departamento_id: 5 )
Municipio.create(nombre: " Panqueba ", departamento_id: 5 )
Municipio.create(nombre: " Pauna ", departamento_id: 5 )
Municipio.create(nombre: " Paya ", departamento_id: 5 )
Municipio.create(nombre: " Paz del Río ", departamento_id: 5 )
Municipio.create(nombre: " Pesca ", departamento_id: 5 )
Municipio.create(nombre: " Pisba ", departamento_id: 5 )
Municipio.create(nombre: " Puerto Boyacá ", departamento_id: 5 )
Municipio.create(nombre: " Quípama ", departamento_id: 5 )
Municipio.create(nombre: " Ramiriquí ", departamento_id: 5 )
Municipio.create(nombre: " Ráquira ", departamento_id: 5 )
Municipio.create(nombre: " Rondón ", departamento_id: 5 )
Municipio.create(nombre: " Saboyá ", departamento_id: 5 )
Municipio.create(nombre: " Sáchica ", departamento_id: 5 )
Municipio.create(nombre: " Samacá ", departamento_id: 5 )
Municipio.create(nombre: " San Eduardo ", departamento_id: 5 )
Municipio.create(nombre: " San José de Pare ", departamento_id: 5 )
Municipio.create(nombre: " San Luis de Gaceno ", departamento_id: 5 )
Municipio.create(nombre: " San Mateo ", departamento_id: 5 )
Municipio.create(nombre: " San Miguel de Sema ", departamento_id: 5 )
Municipio.create(nombre: " San Pablo de Borbur ", departamento_id: 5 )
Municipio.create(nombre: " Santa María ", departamento_id: 5 )
Municipio.create(nombre: " Santa Rosa de Viterbo ", departamento_id: 5 )
Municipio.create(nombre: " Santa Sofía ", departamento_id: 5 )
Municipio.create(nombre: " Santana ", departamento_id: 5 )
Municipio.create(nombre: " Sativanorte ", departamento_id: 5 )
Municipio.create(nombre: " Sativasur ", departamento_id: 5 )
Municipio.create(nombre: " Siachoque ", departamento_id: 5 )
Municipio.create(nombre: " Soatá ", departamento_id: 5 )
Municipio.create(nombre: " Socha ", departamento_id: 5 )
Municipio.create(nombre: " Socotá ", departamento_id: 5 )
Municipio.create(nombre: " Sogamoso ", departamento_id: 5 )
Municipio.create(nombre: " Somondoco ", departamento_id: 5 )
Municipio.create(nombre: " Sora ", departamento_id: 5 )
Municipio.create(nombre: " Soracá ", departamento_id: 5 )
Municipio.create(nombre: " Sotaquirá ", departamento_id: 5 )
Municipio.create(nombre: " Susacón ", departamento_id: 5 )
Municipio.create(nombre: " Sutamarchán ", departamento_id: 5 )
Municipio.create(nombre: " Sutatenza ", departamento_id: 5 )
Municipio.create(nombre: " Tasco ", departamento_id: 5 )
Municipio.create(nombre: " Tenza ", departamento_id: 5 )
Municipio.create(nombre: " Tibaná ", departamento_id: 5 )
Municipio.create(nombre: " Tibasosa ", departamento_id: 5 )
Municipio.create(nombre: " Tinjacá ", departamento_id: 5 )
Municipio.create(nombre: " Tipacoque ", departamento_id: 5 )
Municipio.create(nombre: " Toca ", departamento_id: 5 )
Municipio.create(nombre: " Togüí ", departamento_id: 5 )
Municipio.create(nombre: " Tópaga ", departamento_id: 5 )
Municipio.create(nombre: " Tota ", departamento_id: 5 )
Municipio.create(nombre: " Tunja ", departamento_id: 5 )
Municipio.create(nombre: " Tununguá ", departamento_id: 5 )
Municipio.create(nombre: " Turmequé ", departamento_id: 5 )
Municipio.create(nombre: " Tuta ", departamento_id: 5 )
Municipio.create(nombre: " Tutazá ", departamento_id: 5 )
Municipio.create(nombre: " Úmbita ", departamento_id: 5 )
Municipio.create(nombre: " Ventaquemada ", departamento_id: 5 )
Municipio.create(nombre: " Villa de Leyva ", departamento_id: 5 )
Municipio.create(nombre: " Viracachá ", departamento_id: 5 )
Municipio.create(nombre: " Zetaquira ", departamento_id: 5 )

Municipio.create(nombre: " Aguadas ", departamento_id: 6 )
Municipio.create(nombre: " Anserma ", departamento_id: 6 )
Municipio.create(nombre: " Aranzazu ", departamento_id: 6 )
Municipio.create(nombre: " Belalcázar ", departamento_id: 6 )
Municipio.create(nombre: " Chinchiná ", departamento_id: 6 )
Municipio.create(nombre: " Filadelfia ", departamento_id: 6 )
Municipio.create(nombre: " La Dorada ", departamento_id: 6 )
Municipio.create(nombre: " La Merced ", departamento_id: 6 )
Municipio.create(nombre: " Manizales ", departamento_id: 6 )
Municipio.create(nombre: " Manzanares ", departamento_id: 6 )
Municipio.create(nombre: " Marmato ", departamento_id: 6 )
Municipio.create(nombre: " Marquetalia ", departamento_id: 6 )
Municipio.create(nombre: " Marulanda ", departamento_id: 6 )
Municipio.create(nombre: " Neira ", departamento_id: 6 )
Municipio.create(nombre: " Norcasia ", departamento_id: 6 )
Municipio.create(nombre: " Pácora ", departamento_id: 6 )
Municipio.create(nombre: " Palestina ", departamento_id: 6 )
Municipio.create(nombre: " Pensilvania ", departamento_id: 6 )
Municipio.create(nombre: " Riosucio ", departamento_id: 6 )
Municipio.create(nombre: " Risaralda ", departamento_id: 6 )
Municipio.create(nombre: " Salamina ", departamento_id: 6 )
Municipio.create(nombre: " Samaná ", departamento_id: 6 )
Municipio.create(nombre: " San José ", departamento_id: 6 )
Municipio.create(nombre: " Supía ", departamento_id: 6 )
Municipio.create(nombre: " Victoria ", departamento_id: 6 )
Municipio.create(nombre: " Villamaría ", departamento_id: 6 )
Municipio.create(nombre: " Viterbo ", departamento_id: 6 )

Municipio.create(nombre: " Albania ", departamento_id: 7 )
Municipio.create(nombre: " Belén de los Andaquíes ", departamento_id: 7 )
Municipio.create(nombre: " Cartagena del Chairá ", departamento_id: 7 )
Municipio.create(nombre: " Curillo ", departamento_id: 7 )
Municipio.create(nombre: " El Doncello ", departamento_id: 7 )
Municipio.create(nombre: " El Paujil ", departamento_id: 7 )
Municipio.create(nombre: " Florencia ", departamento_id: 7 )
Municipio.create(nombre: " La Montañita ", departamento_id: 7 )
Municipio.create(nombre: " Milán ", departamento_id: 7 )
Municipio.create(nombre: " Morelia ", departamento_id: 7 )
Municipio.create(nombre: " Puerto Rico ", departamento_id: 7 )
Municipio.create(nombre: " San José del Fragua ", departamento_id: 7 )
Municipio.create(nombre: " San Vicente del Caguán ", departamento_id: 7 )
Municipio.create(nombre: " Solano ", departamento_id: 7 )
Municipio.create(nombre: " Solita ", departamento_id: 7 )
Municipio.create(nombre: " Valparaíso ", departamento_id: 7 )

Municipio.create(nombre: " Aguazul ", departamento_id: 8 )
Municipio.create(nombre: " Chámeza ", departamento_id: 8 )
Municipio.create(nombre: " Hato Corozal ", departamento_id: 8 )
Municipio.create(nombre: " La Salina ", departamento_id: 8 )
Municipio.create(nombre: " Maní ", departamento_id: 8 )
Municipio.create(nombre: " Monterrey ", departamento_id: 8 )
Municipio.create(nombre: " Nunchía ", departamento_id: 8 )
Municipio.create(nombre: " Orocué ", departamento_id: 8 )
Municipio.create(nombre: " Paz de Ariporo ", departamento_id: 8 )
Municipio.create(nombre: " Pore ", departamento_id: 8 )
Municipio.create(nombre: " Recetor ", departamento_id: 8 )
Municipio.create(nombre: " Sabanalarga ", departamento_id: 8 )
Municipio.create(nombre: " Sácama ", departamento_id: 8 )
Municipio.create(nombre: " San Luis de Palenque ", departamento_id: 8 )
Municipio.create(nombre: " Támara ", departamento_id: 8 )
Municipio.create(nombre: " Tauramena ", departamento_id: 8 )
Municipio.create(nombre: " Trinidad ", departamento_id: 8 )
Municipio.create(nombre: " Villanueva ", departamento_id: 8 )
Municipio.create(nombre: " Yopal ", departamento_id: 8 )

Municipio.create(nombre: " Almaguer ", departamento_id: 9 )
Municipio.create(nombre: " Argelia ", departamento_id: 9 )
Municipio.create(nombre: " Balboa ", departamento_id: 9 )
Municipio.create(nombre: " Bolívar ", departamento_id: 9 )
Municipio.create(nombre: " Buenos Aires ", departamento_id: 9 )
Municipio.create(nombre: " Cajibío ", departamento_id: 9 )
Municipio.create(nombre: " Caldono ", departamento_id: 9 )
Municipio.create(nombre: " Caloto ", departamento_id: 9 )
Municipio.create(nombre: " Corinto ", departamento_id: 9 )
Municipio.create(nombre: " El Tambo ", departamento_id: 9 )
Municipio.create(nombre: " Florencia ", departamento_id: 9 )
Municipio.create(nombre: " Guachené ", departamento_id: 9 )
Municipio.create(nombre: " Guapí ", departamento_id: 9 )
Municipio.create(nombre: " Inzá ", departamento_id: 9 )
Municipio.create(nombre: " Jambaló ", departamento_id: 9 )
Municipio.create(nombre: " La Sierra ", departamento_id: 9 )
Municipio.create(nombre: " La Vega ", departamento_id: 9 )
Municipio.create(nombre: " López de Micay ", departamento_id: 9 )
Municipio.create(nombre: " Mercaderes ", departamento_id: 9 )
Municipio.create(nombre: " Miranda ", departamento_id: 9 )
Municipio.create(nombre: " Morales ", departamento_id: 9 )
Municipio.create(nombre: " Padilla ", departamento_id: 9 )
Municipio.create(nombre: " Páez ", departamento_id: 9 )
Municipio.create(nombre: " Patía ", departamento_id: 9 )
Municipio.create(nombre: " Piamonte ", departamento_id: 9 )
Municipio.create(nombre: " Piendamó ", departamento_id: 9 )
Municipio.create(nombre: " Popayán ", departamento_id: 9 )
Municipio.create(nombre: " Puerto Tejada ", departamento_id: 9 )
Municipio.create(nombre: " Puracé ", departamento_id: 9 )
Municipio.create(nombre: " Rosas ", departamento_id: 9 )
Municipio.create(nombre: " San Sebastián ", departamento_id: 9 )
Municipio.create(nombre: " Santa Rosa ", departamento_id: 9 )
Municipio.create(nombre: " Santander de Quilichao ", departamento_id: 9 )
Municipio.create(nombre: " Silvia ", departamento_id: 9 )
Municipio.create(nombre: " Sotará ", departamento_id: 9 )
Municipio.create(nombre: " Suárez ", departamento_id: 9 )
Municipio.create(nombre: " Sucre ", departamento_id: 9 )
Municipio.create(nombre: " Timbío ", departamento_id: 9 )
Municipio.create(nombre: " Timbiquí ", departamento_id: 9 )
Municipio.create(nombre: " Toribío ", departamento_id: 9 )
Municipio.create(nombre: " Totoró ", departamento_id: 9 )
Municipio.create(nombre: " Villa Rica ", departamento_id: 9 )

Municipio.create(nombre: " Aguachica ", departamento_id: 10 )
Municipio.create(nombre: " Agustín Codazzi ", departamento_id: 10 )
Municipio.create(nombre: " Astrea ", departamento_id: 10 )
Municipio.create(nombre: " Becerril ", departamento_id: 10 )
Municipio.create(nombre: " Bosconia ", departamento_id: 10 )
Municipio.create(nombre: " Chimichagua ", departamento_id: 10 )
Municipio.create(nombre: " Chiriguaná ", departamento_id: 10 )
Municipio.create(nombre: " Curumaní ", departamento_id: 10 )
Municipio.create(nombre: " El Copey ", departamento_id: 10 )
Municipio.create(nombre: " El Paso ", departamento_id: 10 )
Municipio.create(nombre: " Gamarra ", departamento_id: 10 )
Municipio.create(nombre: " González ", departamento_id: 10 )
Municipio.create(nombre: " La Gloria (Cesar) ", departamento_id: 10 )
Municipio.create(nombre: " La Jagua de Ibirico ", departamento_id: 10 )
Municipio.create(nombre: " La Paz ", departamento_id: 10 )
Municipio.create(nombre: " Manaure Balcón del Cesar ", departamento_id: 10 )
Municipio.create(nombre: " Pailitas ", departamento_id: 10 )
Municipio.create(nombre: " Pelaya ", departamento_id: 10 )
Municipio.create(nombre: " Pueblo Bello ", departamento_id: 10 )
Municipio.create(nombre: " Río de Oro ", departamento_id: 10 )
Municipio.create(nombre: " San Alberto ", departamento_id: 10 )
Municipio.create(nombre: " San Diego ", departamento_id: 10 )
Municipio.create(nombre: " San Martín ", departamento_id: 10 )
Municipio.create(nombre: " Tamalameque ", departamento_id: 10 )
Municipio.create(nombre: " Valledupar ", departamento_id: 10 )

Municipio.create(nombre: " Acandí ", departamento_id: 11 )
Municipio.create(nombre: " Alto Baudó ", departamento_id: 11 )
Municipio.create(nombre: " Bagadó ", departamento_id: 11 )
Municipio.create(nombre: " Bahía Solano ", departamento_id: 11 )
Municipio.create(nombre: " Bajo Baudó ", departamento_id: 11 )
Municipio.create(nombre: " Bojayá ", departamento_id: 11 )
Municipio.create(nombre: " Cantón de San Pablo ", departamento_id: 11 )
Municipio.create(nombre: " Cértegui ", departamento_id: 11 )
Municipio.create(nombre: " Condoto ", departamento_id: 11 )
Municipio.create(nombre: " El Atrato ", departamento_id: 11 )
Municipio.create(nombre: " El Carmen de Atrato ", departamento_id: 11 )
Municipio.create(nombre: " El Carmen del Darién ", departamento_id: 11 )
Municipio.create(nombre: " Istmina ", departamento_id: 11 )
Municipio.create(nombre: " Juradó ", departamento_id: 11 )
Municipio.create(nombre: " Litoral de San Juan ", departamento_id: 11 )
Municipio.create(nombre: " Lloró ", departamento_id: 11 )
Municipio.create(nombre: " Medio Atrato ", departamento_id: 11 )
Municipio.create(nombre: " Medio Baudó ", departamento_id: 11 )
Municipio.create(nombre: " Medio San Juan ", departamento_id: 11 )
Municipio.create(nombre: " Nóvita ", departamento_id: 11 )
Municipio.create(nombre: " Nuquí ", departamento_id: 11 )
Municipio.create(nombre: " Quibdó ", departamento_id: 11 )
Municipio.create(nombre: " Río Iró ", departamento_id: 11 )
Municipio.create(nombre: " Río Quito ", departamento_id: 11 )
Municipio.create(nombre: " Riosucio ", departamento_id: 11 )
Municipio.create(nombre: " San José del Palmar ", departamento_id: 11 )
Municipio.create(nombre: " Sipí ", departamento_id: 11 )
Municipio.create(nombre: " Tadó ", departamento_id: 11 )
Municipio.create(nombre: " Unión Panamericana ", departamento_id: 11 )
Municipio.create(nombre: " Unguía ", departamento_id: 11 )

Municipio.create(nombre: " Agua de Dios ", departamento_id: 12 )
Municipio.create(nombre: " Albán ", departamento_id: 12 )
Municipio.create(nombre: " Anapoima ", departamento_id: 12 )
Municipio.create(nombre: " Anolaima ", departamento_id: 12 )
Municipio.create(nombre: " Apulo ", departamento_id: 12 )
Municipio.create(nombre: " Arbeláez ", departamento_id: 12 )
Municipio.create(nombre: " Beltrán ", departamento_id: 12 )
Municipio.create(nombre: " Bituima ", departamento_id: 12 )
Municipio.create(nombre: " Bogotá ", departamento_id: 12 )
Municipio.create(nombre: " Bojacá ", departamento_id: 12 )
Municipio.create(nombre: " Cabrera ", departamento_id: 12 )
Municipio.create(nombre: " Cachipay ", departamento_id: 12 )
Municipio.create(nombre: " Cajicá ", departamento_id: 12 )
Municipio.create(nombre: " Caparrapí ", departamento_id: 12 )
Municipio.create(nombre: " Cáqueza ", departamento_id: 12 )
Municipio.create(nombre: " Carmen de Carupa ", departamento_id: 12 )
Municipio.create(nombre: " Chaguaní ", departamento_id: 12 )
Municipio.create(nombre: " Chía ", departamento_id: 12 )
Municipio.create(nombre: " Chipaque ", departamento_id: 12 )
Municipio.create(nombre: " Choachí ", departamento_id: 12 )
Municipio.create(nombre: " Chocontá ", departamento_id: 12 )
Municipio.create(nombre: " Cogua ", departamento_id: 12 )
Municipio.create(nombre: " Cota ", departamento_id: 12 )
Municipio.create(nombre: " Cucunubá ", departamento_id: 12 )
Municipio.create(nombre: " El Colegio ", departamento_id: 12 )
Municipio.create(nombre: " El Peñón ", departamento_id: 12 )
Municipio.create(nombre: " El Rosal ", departamento_id: 12 )
Municipio.create(nombre: " Facatativá ", departamento_id: 12 )
Municipio.create(nombre: " Fómeque ", departamento_id: 12 )
Municipio.create(nombre: " Fosca ", departamento_id: 12 )
Municipio.create(nombre: " Funza ", departamento_id: 12 )
Municipio.create(nombre: " Fúquene ", departamento_id: 12 )
Municipio.create(nombre: " Fusagasugá ", departamento_id: 12 )
Municipio.create(nombre: " Gachalá ", departamento_id: 12 )
Municipio.create(nombre: " Gachancipá ", departamento_id: 12 )
Municipio.create(nombre: " Gachetá ", departamento_id: 12 )
Municipio.create(nombre: " Gama ", departamento_id: 12 )
Municipio.create(nombre: " Girardot ", departamento_id: 12 )
Municipio.create(nombre: " Granada ", departamento_id: 12 )
Municipio.create(nombre: " Guachetá ", departamento_id: 12 )
Municipio.create(nombre: " Guaduas ", departamento_id: 12 )
Municipio.create(nombre: " Guasca ", departamento_id: 12 )
Municipio.create(nombre: " Guataquí ", departamento_id: 12 )
Municipio.create(nombre: " Guatavita ", departamento_id: 12 )
Municipio.create(nombre: " Guayabal de Síquima ", departamento_id: 12 )
Municipio.create(nombre: " Guayabetal ", departamento_id: 12 )
Municipio.create(nombre: " Gutiérrez ", departamento_id: 12 )
Municipio.create(nombre: " Jerusalén ", departamento_id: 12 )
Municipio.create(nombre: " Junín ", departamento_id: 12 )
Municipio.create(nombre: " La Calera ", departamento_id: 12 )
Municipio.create(nombre: " La Mesa ", departamento_id: 12 )
Municipio.create(nombre: " La Palma ", departamento_id: 12 )
Municipio.create(nombre: " La Peña ", departamento_id: 12 )
Municipio.create(nombre: " La Vega ", departamento_id: 12 )
Municipio.create(nombre: " Lenguazaque ", departamento_id: 12 )
Municipio.create(nombre: " Machetá ", departamento_id: 12 )
Municipio.create(nombre: " Madrid ", departamento_id: 12 )
Municipio.create(nombre: " Manta ", departamento_id: 12 )
Municipio.create(nombre: " Medina ", departamento_id: 12 )
Municipio.create(nombre: " Mosquera ", departamento_id: 12 )
Municipio.create(nombre: " Nariño ", departamento_id: 12 )
Municipio.create(nombre: " Nemocón ", departamento_id: 12 )
Municipio.create(nombre: " Nilo ", departamento_id: 12 )
Municipio.create(nombre: " Nimaima ", departamento_id: 12 )
Municipio.create(nombre: " Nocaima ", departamento_id: 12 )
Municipio.create(nombre: " Pacho ", departamento_id: 12 )
Municipio.create(nombre: " Paime ", departamento_id: 12 )
Municipio.create(nombre: " Pandi ", departamento_id: 12 )
Municipio.create(nombre: " Paratebueno ", departamento_id: 12 )
Municipio.create(nombre: " Pasca ", departamento_id: 12 )
Municipio.create(nombre: " Puerto Salgar ", departamento_id: 12 )
Municipio.create(nombre: " Pulí ", departamento_id: 12 )
Municipio.create(nombre: " Quebradanegra ", departamento_id: 12 )
Municipio.create(nombre: " Quetame ", departamento_id: 12 )
Municipio.create(nombre: " Quipile ", departamento_id: 12 )
Municipio.create(nombre: " Ricaurte ", departamento_id: 12 )
Municipio.create(nombre: " San Antonio del Tequendama ", departamento_id: 12 )
Municipio.create(nombre: " San Bernardo ", departamento_id: 12 )
Municipio.create(nombre: " San Cayetano ", departamento_id: 12 )
Municipio.create(nombre: " San Francisco ", departamento_id: 12 )
Municipio.create(nombre: " San Juan de Rioseco ", departamento_id: 12 )
Municipio.create(nombre: " Sasaima ", departamento_id: 12 )
Municipio.create(nombre: " Sesquilé ", departamento_id: 12 )
Municipio.create(nombre: " Sibaté ", departamento_id: 12 )
Municipio.create(nombre: " Silvania ", departamento_id: 12 )
Municipio.create(nombre: " Simijaca ", departamento_id: 12 )
Municipio.create(nombre: " Soacha ", departamento_id: 12 )
Municipio.create(nombre: " Sopó ", departamento_id: 12 )
Municipio.create(nombre: " Subachoque ", departamento_id: 12 )
Municipio.create(nombre: " Suesca ", departamento_id: 12 )
Municipio.create(nombre: " Supatá ", departamento_id: 12 )
Municipio.create(nombre: " Susa ", departamento_id: 12 )
Municipio.create(nombre: " Sutatausa ", departamento_id: 12 )
Municipio.create(nombre: " Tabio ", departamento_id: 12 )
Municipio.create(nombre: " Tausa ", departamento_id: 12 )
Municipio.create(nombre: " Tena ", departamento_id: 12 )
Municipio.create(nombre: " Tenjo ", departamento_id: 12 )
Municipio.create(nombre: " Tibacuy ", departamento_id: 12 )
Municipio.create(nombre: " Tibirita ", departamento_id: 12 )
Municipio.create(nombre: " Tocaima ", departamento_id: 12 )
Municipio.create(nombre: " Tocancipá ", departamento_id: 12 )
Municipio.create(nombre: " Topaipí ", departamento_id: 12 )
Municipio.create(nombre: " Ubalá ", departamento_id: 12 )
Municipio.create(nombre: " Ubaque ", departamento_id: 12 )
Municipio.create(nombre: " Ubaté ", departamento_id: 12 )
Municipio.create(nombre: " Une ", departamento_id: 12 )
Municipio.create(nombre: " Útica ", departamento_id: 12 )
Municipio.create(nombre: " Venecia ", departamento_id: 12 )
Municipio.create(nombre: " Vergara ", departamento_id: 12 )
Municipio.create(nombre: " Vianí ", departamento_id: 12 )
Municipio.create(nombre: " Villagómez ", departamento_id: 12 )
Municipio.create(nombre: " Villapinzón ", departamento_id: 12 )
Municipio.create(nombre: " Villeta ", departamento_id: 12 )
Municipio.create(nombre: " Viotá ", departamento_id: 12 )
Municipio.create(nombre: " Yacopí ", departamento_id: 12 )
Municipio.create(nombre: " Zipacón ", departamento_id: 12 )
Municipio.create(nombre: " Zipaquirá ", departamento_id: 12 )

Municipio.create(nombre: " Ayapel ", departamento_id: 13 )
Municipio.create(nombre: " Buenavista ", departamento_id: 13 )
Municipio.create(nombre: " Canalete ", departamento_id: 13 )
Municipio.create(nombre: " Cereté ", departamento_id: 13 )
Municipio.create(nombre: " Chimá ", departamento_id: 13 )
Municipio.create(nombre: " Chinú ", departamento_id: 13 )
Municipio.create(nombre: " Ciénaga de Oro ", departamento_id: 13 )
Municipio.create(nombre: " Cotorra ", departamento_id: 13 )
Municipio.create(nombre: " La Apartada ", departamento_id: 13 )
Municipio.create(nombre: " Lorica ", departamento_id: 13 )
Municipio.create(nombre: " Los Córdobas ", departamento_id: 13 )
Municipio.create(nombre: " Momil ", departamento_id: 13 )
Municipio.create(nombre: " Montelíbano ", departamento_id: 13 )
Municipio.create(nombre: " Montería ", departamento_id: 13 )
Municipio.create(nombre: " Moñitos ", departamento_id: 13 )
Municipio.create(nombre: " Planeta Rica ", departamento_id: 13 )
Municipio.create(nombre: " Pueblo Nuevo ", departamento_id: 13 )
Municipio.create(nombre: " Puerto Escondido ", departamento_id: 13 )
Municipio.create(nombre: " Puerto Libertador ", departamento_id: 13 )
Municipio.create(nombre: " Purísima ", departamento_id: 13 )
Municipio.create(nombre: " Sahagún ", departamento_id: 13 )
Municipio.create(nombre: " San Andrés de Sotavento ", departamento_id: 13 )
Municipio.create(nombre: " San Antero ", departamento_id: 13 )
Municipio.create(nombre: " San Bernardo del Viento ", departamento_id: 13 )
Municipio.create(nombre: " San Carlos ", departamento_id: 13 )
Municipio.create(nombre: " San José de Uré ", departamento_id: 13 )
Municipio.create(nombre: " San Pelayo ", departamento_id: 13 )
Municipio.create(nombre: " Tierralta ", departamento_id: 13 )
Municipio.create(nombre: " Tuchín ", departamento_id: 13 )
Municipio.create(nombre: " Valencia ", departamento_id: 13 )

Municipio.create(nombre: " Inírida ", departamento_id: 14 )

Municipio.create(nombre: " Calamar ", departamento_id: 15 )
Municipio.create(nombre: " El Retorno ", departamento_id: 15 )
Municipio.create(nombre: " Miraflores ", departamento_id: 15 )
Municipio.create(nombre: " San José del Guaviare ", departamento_id: 15 )

Municipio.create(nombre: " Acevedo ", departamento_id: 16 )
Municipio.create(nombre: " Agrado ", departamento_id: 16 )
Municipio.create(nombre: " Aipe ", departamento_id: 16 )
Municipio.create(nombre: " Algeciras ", departamento_id: 16 )
Municipio.create(nombre: " Altamira ", departamento_id: 16 )
Municipio.create(nombre: " Baraya ", departamento_id: 16 )
Municipio.create(nombre: " Campoalegre ", departamento_id: 16 )
Municipio.create(nombre: " Colombia ", departamento_id: 16 )
Municipio.create(nombre: " El Pital ", departamento_id: 16 )
Municipio.create(nombre: " Elías ", departamento_id: 16 )
Municipio.create(nombre: " Garzón ", departamento_id: 16 )
Municipio.create(nombre: " Gigante ", departamento_id: 16 )
Municipio.create(nombre: " Guadalupe ", departamento_id: 16 )
Municipio.create(nombre: " Hobo ", departamento_id: 16 )
Municipio.create(nombre: " Íquira ", departamento_id: 16 )
Municipio.create(nombre: " Isnos ", departamento_id: 16 )
Municipio.create(nombre: " La Argentina ", departamento_id: 16 )
Municipio.create(nombre: " La Plata ", departamento_id: 16 )
Municipio.create(nombre: " Nátaga ", departamento_id: 16 )
Municipio.create(nombre: " Neiva ", departamento_id: 16 )
Municipio.create(nombre: " Oporapa ", departamento_id: 16 )
Municipio.create(nombre: " Paicol ", departamento_id: 16 )
Municipio.create(nombre: " Palermo ", departamento_id: 16 )
Municipio.create(nombre: " Palestina ", departamento_id: 16 )
Municipio.create(nombre: " Pitalito ", departamento_id: 16 )
Municipio.create(nombre: " Rivera ", departamento_id: 16 )
Municipio.create(nombre: " Saladoblanco ", departamento_id: 16 )
Municipio.create(nombre: " San Agustín ", departamento_id: 16 )
Municipio.create(nombre: " Santa María ", departamento_id: 16 )
Municipio.create(nombre: " Suaza ", departamento_id: 16 )
Municipio.create(nombre: " Tarqui ", departamento_id: 16 )
Municipio.create(nombre: " Tello ", departamento_id: 16 )
Municipio.create(nombre: " Teruel ", departamento_id: 16 )
Municipio.create(nombre: " Tesalia ", departamento_id: 16 )
Municipio.create(nombre: " Timaná ", departamento_id: 16 )
Municipio.create(nombre: " Villavieja ", departamento_id: 16 )
Municipio.create(nombre: " Yaguará ", departamento_id: 16 )

Municipio.create(nombre: " Albania ", departamento_id: 17 )
Municipio.create(nombre: " Barrancas ", departamento_id: 17 )
Municipio.create(nombre: " Dibulla ", departamento_id: 17 )
Municipio.create(nombre: " Distracción ", departamento_id: 17 )
Municipio.create(nombre: " El Molino ", departamento_id: 17 )
Municipio.create(nombre: " Fonseca ", departamento_id: 17 )
Municipio.create(nombre: " Hatonuevo ", departamento_id: 17 )
Municipio.create(nombre: " La Jagua del Pilar ", departamento_id: 17 )
Municipio.create(nombre: " Maicao ", departamento_id: 17 )
Municipio.create(nombre: " Manaure ", departamento_id: 17 )
Municipio.create(nombre: " Riohacha ", departamento_id: 17 )
Municipio.create(nombre: " San Juan del Cesar ", departamento_id: 17 )
Municipio.create(nombre: " Uribia ", departamento_id: 17 )
Municipio.create(nombre: " Urumita ", departamento_id: 17 )
Municipio.create(nombre: " Villanueva ", departamento_id: 17 )

Municipio.create(nombre: " Algarrobo ", departamento_id: 18 )
Municipio.create(nombre: " Aracataca ", departamento_id: 18 )
Municipio.create(nombre: " Ariguaní ", departamento_id: 18 )
Municipio.create(nombre: " Cerro de San Antonio ", departamento_id: 18 )
Municipio.create(nombre: " Chibolo ", departamento_id: 18 )
Municipio.create(nombre: " Chibolo ", departamento_id: 18 )
Municipio.create(nombre: " Ciénaga ", departamento_id: 18 )
Municipio.create(nombre: " Concordia ", departamento_id: 18 )
Municipio.create(nombre: " El Banco ", departamento_id: 18 )
Municipio.create(nombre: " El Piñón ", departamento_id: 18 )
Municipio.create(nombre: " El Retén ", departamento_id: 18 )
Municipio.create(nombre: " Fundación ", departamento_id: 18 )
Municipio.create(nombre: " Guamal ", departamento_id: 18 )
Municipio.create(nombre: " Nueva Granada ", departamento_id: 18 )
Municipio.create(nombre: " Pedraza ", departamento_id: 18 )
Municipio.create(nombre: " Pijiño del Carmen ", departamento_id: 18 )
Municipio.create(nombre: " Pivijay ", departamento_id: 18 )
Municipio.create(nombre: " Plato ", departamento_id: 18 )
Municipio.create(nombre: " Pueblo Viejo ", departamento_id: 18 )
Municipio.create(nombre: " Remolino ", departamento_id: 18 )
Municipio.create(nombre: " Sabanas de San Ángel ", departamento_id: 18 )
Municipio.create(nombre: " Salamina ", departamento_id: 18 )
Municipio.create(nombre: " San Sebastián de Buenavista ", departamento_id: 18 )
Municipio.create(nombre: " San Zenón ", departamento_id: 18 )
Municipio.create(nombre: " Santa Ana ", departamento_id: 18 )
Municipio.create(nombre: " Santa Bárbara de Pinto ", departamento_id: 18 )
Municipio.create(nombre: " Santa Marta ", departamento_id: 18 )
Municipio.create(nombre: " Sitionuevo ", departamento_id: 18 )
Municipio.create(nombre: " Tenerife ", departamento_id: 18 )
Municipio.create(nombre: " Zapayán ", departamento_id: 18 )
Municipio.create(nombre: " Zona Bananera ", departamento_id: 18 )

Municipio.create(nombre: " Acacías ", departamento_id: 19 )
Municipio.create(nombre: " Barranca de Upía ", departamento_id: 19 )
Municipio.create(nombre: " Cabuyaro ", departamento_id: 19 )
Municipio.create(nombre: " Castilla la Nueva ", departamento_id: 19 )
Municipio.create(nombre: " Cubarral ", departamento_id: 19 )
Municipio.create(nombre: " Cumaral ", departamento_id: 19 )
Municipio.create(nombre: " El Calvario ", departamento_id: 19 )
Municipio.create(nombre: " El Castillo ", departamento_id: 19 )
Municipio.create(nombre: " El Dorado ", departamento_id: 19 )
Municipio.create(nombre: " Fuente de Oro ", departamento_id: 19 )
Municipio.create(nombre: " Granada ", departamento_id: 19 )
Municipio.create(nombre: " Guamal ", departamento_id: 19 )
Municipio.create(nombre: " La Macarena ", departamento_id: 19 )
Municipio.create(nombre: " La Uribe ", departamento_id: 19 )
Municipio.create(nombre: " Lejanías ", departamento_id: 19 )
Municipio.create(nombre: " Mapiripán ", departamento_id: 19 )
Municipio.create(nombre: " Mesetas ", departamento_id: 19 )
Municipio.create(nombre: " Puerto Concordia ", departamento_id: 19 )
Municipio.create(nombre: " Puerto Gaitán ", departamento_id: 19 )
Municipio.create(nombre: " Puerto Lleras ", departamento_id: 19 )
Municipio.create(nombre: " Puerto López ", departamento_id: 19 )
Municipio.create(nombre: " Puerto Rico ", departamento_id: 19 )
Municipio.create(nombre: " Restrepo ", departamento_id: 19 )
Municipio.create(nombre: " San Carlos de Guaroa ", departamento_id: 19 )
Municipio.create(nombre: " San Juan de Arama ", departamento_id: 19 )
Municipio.create(nombre: " San Juanito ", departamento_id: 19 )
Municipio.create(nombre: " San Martín ", departamento_id: 19 )
Municipio.create(nombre: " Villavicencio ", departamento_id: 19 )
Municipio.create(nombre: " Vista Hermosa ", departamento_id: 19 )

Municipio.create(nombre: " Aldana ", departamento_id: 20 )
Municipio.create(nombre: " Ancuyá ", departamento_id: 20 )
Municipio.create(nombre: " Arboleda ", departamento_id: 20 )
Municipio.create(nombre: " Barbacoas ", departamento_id: 20 )
Municipio.create(nombre: " Belén ", departamento_id: 20 )
Municipio.create(nombre: " Buesaco ", departamento_id: 20 )
Municipio.create(nombre: " Chachagüí ", departamento_id: 20 )
Municipio.create(nombre: " Colón ", departamento_id: 20 )
Municipio.create(nombre: " Consacá ", departamento_id: 20 )
Municipio.create(nombre: " Contadero ", departamento_id: 20 )
Municipio.create(nombre: " Córdoba ", departamento_id: 20 )
Municipio.create(nombre: " Cuaspud ", departamento_id: 20 )
Municipio.create(nombre: " Cumbal ", departamento_id: 20 )
Municipio.create(nombre: " Cumbitara ", departamento_id: 20 )
Municipio.create(nombre: " El Charco ", departamento_id: 20 )
Municipio.create(nombre: " El Peñol ", departamento_id: 20 )
Municipio.create(nombre: " El Rosario ", departamento_id: 20 )
Municipio.create(nombre: " El Tablón ", departamento_id: 20 )
Municipio.create(nombre: " El Tambo ", departamento_id: 20 )
Municipio.create(nombre: " Francisco Pizarro ", departamento_id: 20 )
Municipio.create(nombre: " Funes ", departamento_id: 20 )
Municipio.create(nombre: " Guachucal ", departamento_id: 20 )
Municipio.create(nombre: " Guaitarilla ", departamento_id: 20 )
Municipio.create(nombre: " Gualmatán ", departamento_id: 20 )
Municipio.create(nombre: " Iles ", departamento_id: 20 )
Municipio.create(nombre: " Imués ", departamento_id: 20 )
Municipio.create(nombre: " Ipiales ", departamento_id: 20 )
Municipio.create(nombre: " La Cruz ", departamento_id: 20 )
Municipio.create(nombre: " La Florida ", departamento_id: 20 )
Municipio.create(nombre: " La Llanada ", departamento_id: 20 )
Municipio.create(nombre: " La Tola ", departamento_id: 20 )
Municipio.create(nombre: " La Unión ", departamento_id: 20 )
Municipio.create(nombre: " Leiva ", departamento_id: 20 )
Municipio.create(nombre: " Linares ", departamento_id: 20 )
Municipio.create(nombre: " Los Andes ", departamento_id: 20 )
Municipio.create(nombre: " Magüí Payán ", departamento_id: 20 )
Municipio.create(nombre: " Mallama ", departamento_id: 20 )
Municipio.create(nombre: " Mosquera ", departamento_id: 20 )
Municipio.create(nombre: " Nariño ", departamento_id: 20 )
Municipio.create(nombre: " Olaya Herrera ", departamento_id: 20 )
Municipio.create(nombre: " Ospina ", departamento_id: 20 )
Municipio.create(nombre: " Pasto ", departamento_id: 20 )
Municipio.create(nombre: " Policarpa ", departamento_id: 20 )
Municipio.create(nombre: " Potosí ", departamento_id: 20 )
Municipio.create(nombre: " Providencia ", departamento_id: 20 )
Municipio.create(nombre: " Puerres ", departamento_id: 20 )
Municipio.create(nombre: " Pupiales ", departamento_id: 20 )
Municipio.create(nombre: " Ricaurte ", departamento_id: 20 )
Municipio.create(nombre: " Roberto Payán ", departamento_id: 20 )
Municipio.create(nombre: " Samaniego ", departamento_id: 20 )
Municipio.create(nombre: " San Bernardo ", departamento_id: 20 )
Municipio.create(nombre: " San José de Albán ", departamento_id: 20 )
Municipio.create(nombre: " San Lorenzo ", departamento_id: 20 )
Municipio.create(nombre: " San Pablo ", departamento_id: 20 )
Municipio.create(nombre: " San Pedro de Cartago ", departamento_id: 20 )
Municipio.create(nombre: " Sandoná ", departamento_id: 20 )
Municipio.create(nombre: " Santa Bárbara ", departamento_id: 20 )
Municipio.create(nombre: " Santacruz ", departamento_id: 20 )
Municipio.create(nombre: " Sapuyes ", departamento_id: 20 )
Municipio.create(nombre: " Taminango ", departamento_id: 20 )
Municipio.create(nombre: " Tangua ", departamento_id: 20 )
Municipio.create(nombre: " Tumaco ", departamento_id: 20 )
Municipio.create(nombre: " Túquerres ", departamento_id: 20 )
Municipio.create(nombre: " Yacuanquer ", departamento_id: 20 )

Municipio.create(nombre: " Ábrego ", departamento_id: 21 )
Municipio.create(nombre: " Arboledas ", departamento_id: 21 )
Municipio.create(nombre: " Bochalema ", departamento_id: 21 )
Municipio.create(nombre: " Bucarasica ", departamento_id: 21 )
Municipio.create(nombre: " Cáchira ", departamento_id: 21 )
Municipio.create(nombre: " Cácota ", departamento_id: 21 )
Municipio.create(nombre: " Chinácota ", departamento_id: 21 )
Municipio.create(nombre: " Chitagá ", departamento_id: 21 )
Municipio.create(nombre: " Convención ", departamento_id: 21 )
Municipio.create(nombre: " Cúcuta ", departamento_id: 21 )
Municipio.create(nombre: " Cucutilla ", departamento_id: 21 )
Municipio.create(nombre: " Duranía ", departamento_id: 21 )
Municipio.create(nombre: " El Carmen ", departamento_id: 21 )
Municipio.create(nombre: " El Tarra ", departamento_id: 21 )
Municipio.create(nombre: " El Zulia ", departamento_id: 21 )
Municipio.create(nombre: " Gramalote ", departamento_id: 21 )
Municipio.create(nombre: " Hacarí ", departamento_id: 21 )
Municipio.create(nombre: " Herrán ", departamento_id: 21 )
Municipio.create(nombre: " La Esperanza ", departamento_id: 21 )
Municipio.create(nombre: " La Playa de Belén ", departamento_id: 21 )
Municipio.create(nombre: " Labateca ", departamento_id: 21 )
Municipio.create(nombre: " Los Patios ", departamento_id: 21 )
Municipio.create(nombre: " Lourdes ", departamento_id: 21 )
Municipio.create(nombre: " Mutiscua ", departamento_id: 21 )
Municipio.create(nombre: " Ocaña ", departamento_id: 21 )
Municipio.create(nombre: " Pamplona ", departamento_id: 21 )
Municipio.create(nombre: " Pamplonita ", departamento_id: 21 )
Municipio.create(nombre: " Puerto Santander ", departamento_id: 21 )
Municipio.create(nombre: " Ragonvalia ", departamento_id: 21 )
Municipio.create(nombre: " Salazar de Las Palmas ", departamento_id: 21 )
Municipio.create(nombre: " San Calixto ", departamento_id: 21 )
Municipio.create(nombre: " San Cayetano ", departamento_id: 21 )
Municipio.create(nombre: " Santiago ", departamento_id: 21 )
Municipio.create(nombre: " Santo Domingo de Silos ", departamento_id: 21 )
Municipio.create(nombre: " Sardinata ", departamento_id: 21 )
Municipio.create(nombre: " Teorama ", departamento_id: 21 )
Municipio.create(nombre: " Tibú ", departamento_id: 21 )
Municipio.create(nombre: " Toledo ", departamento_id: 21 )
Municipio.create(nombre: " Villa Caro ", departamento_id: 21 )
Municipio.create(nombre: " Villa del Rosario ", departamento_id: 21 )

Municipio.create(nombre: " Colón ", departamento_id: 22 )
Municipio.create(nombre: " Mocoa ", departamento_id: 22 )
Municipio.create(nombre: " Orito ", departamento_id: 22 )
Municipio.create(nombre: " Puerto Asís ", departamento_id: 22 )
Municipio.create(nombre: " Puerto Caicedo ", departamento_id: 22 )
Municipio.create(nombre: " Puerto Guzmán ", departamento_id: 22 )
Municipio.create(nombre: " Puerto Leguízamo ", departamento_id: 22 )
Municipio.create(nombre: " San Francisco ", departamento_id: 22 )
Municipio.create(nombre: " San Miguel ", departamento_id: 22 )
Municipio.create(nombre: " Santiago ", departamento_id: 22 )
Municipio.create(nombre: " Sibundoy ", departamento_id: 22 )
Municipio.create(nombre: " Valle del Guamuez ", departamento_id: 22 )
Municipio.create(nombre: " Villagarzón ", departamento_id: 22 )

Municipio.create(nombre: " Armenia ", departamento_id: 23 )
Municipio.create(nombre: " Buenavista ", departamento_id: 23 )
Municipio.create(nombre: " Calarcá ", departamento_id: 23 )
Municipio.create(nombre: " Circasia ", departamento_id: 23 )
Municipio.create(nombre: " Córdoba ", departamento_id: 23 )
Municipio.create(nombre: " Filandia ", departamento_id: 23 )
Municipio.create(nombre: " Génova ", departamento_id: 23 )
Municipio.create(nombre: " La Tebaida ", departamento_id: 23 )
Municipio.create(nombre: " Montenegro ", departamento_id: 23 )
Municipio.create(nombre: " Pijao ", departamento_id: 23 )
Municipio.create(nombre: " Quimbaya ", departamento_id: 23 )
Municipio.create(nombre: " Salento ", departamento_id: 23 )

Municipio.create(nombre: " Apía ", departamento_id: 24 )
Municipio.create(nombre: " Balboa ", departamento_id: 24 )
Municipio.create(nombre: " Belén de Umbría ", departamento_id: 24 )
Municipio.create(nombre: " Dosquebradas ", departamento_id: 24 )
Municipio.create(nombre: " Guática ", departamento_id: 24 )
Municipio.create(nombre: " La Celia ", departamento_id: 24 )
Municipio.create(nombre: " La Virginia ", departamento_id: 24 )
Municipio.create(nombre: " Marsella ", departamento_id: 24 )
Municipio.create(nombre: " Mistrató ", departamento_id: 24 )
Municipio.create(nombre: " Pereira ", departamento_id: 24 )
Municipio.create(nombre: " Pueblo Rico ", departamento_id: 24 )
Municipio.create(nombre: " Quinchía ", departamento_id: 24 )
Municipio.create(nombre: " Santa Rosa de Cabal ", departamento_id: 24 )
Municipio.create(nombre: " Santuario ", departamento_id: 24 )

Municipio.create(nombre: " Providencia y Santa Catalina Islas ", departamento_id: 25 )
Municipio.create(nombre: " San Andrés ", departamento_id: 25 )

Municipio.create(nombre: " Aguada ", departamento_id: 26 )
Municipio.create(nombre: " Albania ", departamento_id: 26 )
Municipio.create(nombre: " Aratoca ", departamento_id: 26 )
Municipio.create(nombre: " Barbosa ", departamento_id: 26 )
Municipio.create(nombre: " Barichara ", departamento_id: 26 )
Municipio.create(nombre: " Barrancabermeja ", departamento_id: 26 )
Municipio.create(nombre: " Betulia ", departamento_id: 26 )
Municipio.create(nombre: " Bolívar ", departamento_id: 26 )
Municipio.create(nombre: " Bucaramanga ", departamento_id: 26 )
Municipio.create(nombre: " Cabrera ", departamento_id: 26 )
Municipio.create(nombre: " California ", departamento_id: 26 )
Municipio.create(nombre: " Capitanejo ", departamento_id: 26 )
Municipio.create(nombre: " Carcasí ", departamento_id: 26 )
Municipio.create(nombre: " Cepitá ", departamento_id: 26 )
Municipio.create(nombre: " Cerrito ", departamento_id: 26 )
Municipio.create(nombre: " Charalá ", departamento_id: 26 )
Municipio.create(nombre: " Charta ", departamento_id: 26 )
Municipio.create(nombre: " Chima ", departamento_id: 26 )
Municipio.create(nombre: " Chipatá ", departamento_id: 26 )
Municipio.create(nombre: " Cimitarra ", departamento_id: 26 )
Municipio.create(nombre: " Concepción ", departamento_id: 26 )
Municipio.create(nombre: " Confines ", departamento_id: 26 )
Municipio.create(nombre: " Contratación ", departamento_id: 26 )
Municipio.create(nombre: " Coromoro ", departamento_id: 26 )
Municipio.create(nombre: " Curití ", departamento_id: 26 )
Municipio.create(nombre: " El Carmen de Chucurí ", departamento_id: 26 )
Municipio.create(nombre: " El Guacamayo ", departamento_id: 26 )
Municipio.create(nombre: " El Peñón ", departamento_id: 26 )
Municipio.create(nombre: " El Playón ", departamento_id: 26 )
Municipio.create(nombre: " El Socorro ", departamento_id: 26 )
Municipio.create(nombre: " Encino ", departamento_id: 26 )
Municipio.create(nombre: " Enciso ", departamento_id: 26 )
Municipio.create(nombre: " Florián ", departamento_id: 26 )
Municipio.create(nombre: " Floridablanca ", departamento_id: 26 )
Municipio.create(nombre: " Galán ", departamento_id: 26 )
Municipio.create(nombre: " Gámbita ", departamento_id: 26 )
Municipio.create(nombre: " Girón ", departamento_id: 26 )
Municipio.create(nombre: " Guaca ", departamento_id: 26 )
Municipio.create(nombre: " Guadalupe ", departamento_id: 26 )
Municipio.create(nombre: " Guapotá ", departamento_id: 26 )
Municipio.create(nombre: " Guavatá ", departamento_id: 26 )
Municipio.create(nombre: " Güepsa ", departamento_id: 26 )
Municipio.create(nombre: " Hato ", departamento_id: 26 )
Municipio.create(nombre: " Jesús María ", departamento_id: 26 )
Municipio.create(nombre: " Jordán ", departamento_id: 26 )
Municipio.create(nombre: " La Belleza ", departamento_id: 26 )
Municipio.create(nombre: " La Paz ", departamento_id: 26 )
Municipio.create(nombre: " Landázuri ", departamento_id: 26 )
Municipio.create(nombre: " Lebrija ", departamento_id: 26 )
Municipio.create(nombre: " Los Santos ", departamento_id: 26 )
Municipio.create(nombre: " Macaravita ", departamento_id: 26 )
Municipio.create(nombre: " Málaga ", departamento_id: 26 )
Municipio.create(nombre: " Matanza ", departamento_id: 26 )
Municipio.create(nombre: " Mogotes ", departamento_id: 26 )
Municipio.create(nombre: " Molagavita ", departamento_id: 26 )
Municipio.create(nombre: " Ocamonte ", departamento_id: 26 )
Municipio.create(nombre: " Oiba ", departamento_id: 26 )
Municipio.create(nombre: " Onzaga ", departamento_id: 26 )
Municipio.create(nombre: " Palmar ", departamento_id: 26 )
Municipio.create(nombre: " Palmas del Socorro ", departamento_id: 26 )
Municipio.create(nombre: " Páramo ", departamento_id: 26 )
Municipio.create(nombre: " Piedecuesta ", departamento_id: 26 )
Municipio.create(nombre: " Pinchote ", departamento_id: 26 )
Municipio.create(nombre: " Puente Nacional ", departamento_id: 26 )
Municipio.create(nombre: " Puerto Parra ", departamento_id: 26 )
Municipio.create(nombre: " Puerto Wilches ", departamento_id: 26 )
Municipio.create(nombre: " Rionegro ", departamento_id: 26 )
Municipio.create(nombre: " Sabana de Torres ", departamento_id: 26 )
Municipio.create(nombre: " San Andrés ", departamento_id: 26 )
Municipio.create(nombre: " San Benito ", departamento_id: 26 )
Municipio.create(nombre: " San Gil ", departamento_id: 26 )
Municipio.create(nombre: " San Joaquín ", departamento_id: 26 )
Municipio.create(nombre: " San José de Miranda ", departamento_id: 26 )
Municipio.create(nombre: " San Miguel ", departamento_id: 26 )
Municipio.create(nombre: " San Vicente de Chucurí ", departamento_id: 26 )
Municipio.create(nombre: " Santa Bárbara ", departamento_id: 26 )
Municipio.create(nombre: " Santa Helena del Opón ", departamento_id: 26 )
Municipio.create(nombre: " Simacota ", departamento_id: 26 )
Municipio.create(nombre: " Suaita ", departamento_id: 26 )
Municipio.create(nombre: " Sucre ", departamento_id: 26 )
Municipio.create(nombre: " Suratá ", departamento_id: 26 )
Municipio.create(nombre: " Tona ", departamento_id: 26 )
Municipio.create(nombre: " Valle de San José ", departamento_id: 26 )
Municipio.create(nombre: " Vélez ", departamento_id: 26 )
Municipio.create(nombre: " Vetas ", departamento_id: 26 )
Municipio.create(nombre: " Villanueva ", departamento_id: 26 )
Municipio.create(nombre: " Zapatoca ", departamento_id: 26 )

Municipio.create(nombre: " Buenavista ", departamento_id: 27 )
Municipio.create(nombre: " Caimito ", departamento_id: 27 )
Municipio.create(nombre: " Chalán ", departamento_id: 27 )
Municipio.create(nombre: " Colosó ", departamento_id: 27 )
Municipio.create(nombre: " Corozal ", departamento_id: 27 )
Municipio.create(nombre: " Coveñas ", departamento_id: 27 )
Municipio.create(nombre: " El Roble ", departamento_id: 27 )
Municipio.create(nombre: " Galeras ", departamento_id: 27 )
Municipio.create(nombre: " Guaranda ", departamento_id: 27 )
Municipio.create(nombre: " La Unión ", departamento_id: 27 )
Municipio.create(nombre: " Los Palmitos ", departamento_id: 27 )
Municipio.create(nombre: " Majagual ", departamento_id: 27 )
Municipio.create(nombre: " Morroa ", departamento_id: 27 )
Municipio.create(nombre: " Ovejas ", departamento_id: 27 )
Municipio.create(nombre: " Sampués ", departamento_id: 27 )
Municipio.create(nombre: " San Antonio de Palmito ", departamento_id: 27 )
Municipio.create(nombre: " San Benito Abad ", departamento_id: 27 )
Municipio.create(nombre: " San Juan de Betulia ", departamento_id: 27 )
Municipio.create(nombre: " San Marcos ", departamento_id: 27 )
Municipio.create(nombre: " San Onofre ", departamento_id: 27 )
Municipio.create(nombre: " San Pedro ", departamento_id: 27 )
Municipio.create(nombre: " Sincé ", departamento_id: 27 )
Municipio.create(nombre: " Sincelejo ", departamento_id: 27 )
Municipio.create(nombre: " Sucre ", departamento_id: 27 )
Municipio.create(nombre: " Tolú ", departamento_id: 27 )
Municipio.create(nombre: " Tolú Viejo ", departamento_id: 27 )

Municipio.create(nombre: " Alpujarra ", departamento_id: 28 )
Municipio.create(nombre: " Alvarado ", departamento_id: 28 )
Municipio.create(nombre: " Ambalema ", departamento_id: 28 )
Municipio.create(nombre: " Anzoátegui ", departamento_id: 28 )
Municipio.create(nombre: " Armero ", departamento_id: 28 )
Municipio.create(nombre: " Ataco ", departamento_id: 28 )
Municipio.create(nombre: " Cajamarca ", departamento_id: 28 )
Municipio.create(nombre: " Carmen de Apicalá ", departamento_id: 28 )
Municipio.create(nombre: " Casabianca ", departamento_id: 28 )
Municipio.create(nombre: " Chaparral ", departamento_id: 28 )
Municipio.create(nombre: " Coello ", departamento_id: 28 )
Municipio.create(nombre: " Coyaima ", departamento_id: 28 )
Municipio.create(nombre: " Cunday ", departamento_id: 28 )
Municipio.create(nombre: " Dolores ", departamento_id: 28 )
Municipio.create(nombre: " El Espinal ", departamento_id: 28 )
Municipio.create(nombre: " Falán ", departamento_id: 28 )
Municipio.create(nombre: " Flandes ", departamento_id: 28 )
Municipio.create(nombre: " Fresno ", departamento_id: 28 )
Municipio.create(nombre: " Guamo ", departamento_id: 28 )
Municipio.create(nombre: " Herveo ", departamento_id: 28 )
Municipio.create(nombre: " Honda ", departamento_id: 28 )
Municipio.create(nombre: " Ibagué ", departamento_id: 28 )
Municipio.create(nombre: " Icononzo ", departamento_id: 28 )
Municipio.create(nombre: " Lérida ", departamento_id: 28 )
Municipio.create(nombre: " Líbano ", departamento_id: 28 )
Municipio.create(nombre: " Mariquita ", departamento_id: 28 )
Municipio.create(nombre: " Melgar ", departamento_id: 28 )
Municipio.create(nombre: " Murillo ", departamento_id: 28 )
Municipio.create(nombre: " Natagaima ", departamento_id: 28 )
Municipio.create(nombre: " Ortega ", departamento_id: 28 )
Municipio.create(nombre: " Palocabildo ", departamento_id: 28 )
Municipio.create(nombre: " Piedras ", departamento_id: 28 )
Municipio.create(nombre: " Planadas ", departamento_id: 28 )
Municipio.create(nombre: " Prado ", departamento_id: 28 )
Municipio.create(nombre: " Purificación ", departamento_id: 28 )
Municipio.create(nombre: " Rioblanco ", departamento_id: 28 )
Municipio.create(nombre: " Roncesvalles ", departamento_id: 28 )
Municipio.create(nombre: " Rovira ", departamento_id: 28 )
Municipio.create(nombre: " Saldaña ", departamento_id: 28 )
Municipio.create(nombre: " San Antonio ", departamento_id: 28 )
Municipio.create(nombre: " San Luis ", departamento_id: 28 )
Municipio.create(nombre: " Santa Isabel ", departamento_id: 28 )
Municipio.create(nombre: " Suárez ", departamento_id: 28 )
Municipio.create(nombre: " Valle de San Juan ", departamento_id: 28 )
Municipio.create(nombre: " Venadillo ", departamento_id: 28 )
Municipio.create(nombre: " Villahermosa ", departamento_id: 28 )
Municipio.create(nombre: " Villarrica ", departamento_id: 28 )

Municipio.create(nombre: " Alcalá ", departamento_id: 29 )
Municipio.create(nombre: " Andalucía ", departamento_id: 29 )
Municipio.create(nombre: " Ansermanuevo ", departamento_id: 29 )
Municipio.create(nombre: " Argelia ", departamento_id: 29 )
Municipio.create(nombre: " Bolívar ", departamento_id: 29 )
Municipio.create(nombre: " Buenaventura ", departamento_id: 29 )
Municipio.create(nombre: " Buga ", departamento_id: 29 )
Municipio.create(nombre: " Bugalagrande ", departamento_id: 29 )
Municipio.create(nombre: " Caicedonia ", departamento_id: 29 )
Municipio.create(nombre: " Cali ", departamento_id: 29 )
Municipio.create(nombre: " Calima ", departamento_id: 29 )
Municipio.create(nombre: " Candelaria ", departamento_id: 29 )
Municipio.create(nombre: " Cartago ", departamento_id: 29 )
Municipio.create(nombre: " Dagua ", departamento_id: 29 )
Municipio.create(nombre: " El Águila ", departamento_id: 29 )
Municipio.create(nombre: " El Cairo ", departamento_id: 29 )
Municipio.create(nombre: " El Cerrito ", departamento_id: 29 )
Municipio.create(nombre: " El Dovio ", departamento_id: 29 )
Municipio.create(nombre: " Florida ", departamento_id: 29 )
Municipio.create(nombre: " Ginebra ", departamento_id: 29 )
Municipio.create(nombre: " Guacarí ", departamento_id: 29 )
Municipio.create(nombre: " Jamundí ", departamento_id: 29 )
Municipio.create(nombre: " La Cumbre ", departamento_id: 29 )
Municipio.create(nombre: " La Unión ", departamento_id: 29 )
Municipio.create(nombre: " La Victoria ", departamento_id: 29 )

Municipio.create(nombre: " Obando ", departamento_id: 29 )
Municipio.create(nombre: " Palmira ", departamento_id: 29 )
Municipio.create(nombre: " Pradera ", departamento_id: 29 )
Municipio.create(nombre: " Restrepo ", departamento_id: 29 )
Municipio.create(nombre: " Riofrío ", departamento_id: 29 )
Municipio.create(nombre: " Roldanillo ", departamento_id: 29 )
Municipio.create(nombre: " San Pedro ", departamento_id: 29 )
Municipio.create(nombre: " Sevilla ", departamento_id: 29 )
Municipio.create(nombre: " Toro ", departamento_id: 29 )
Municipio.create(nombre: " Trujillo ", departamento_id: 29 )
Municipio.create(nombre: " Tuluá ", departamento_id: 29 )
Municipio.create(nombre: " Ulloa ", departamento_id: 29 )
Municipio.create(nombre: " Versalles ", departamento_id: 29 )
Municipio.create(nombre: " Vijes ", departamento_id: 29 )
Municipio.create(nombre: " Yotoco ", departamento_id: 29 )
Municipio.create(nombre: " Yumbo ", departamento_id: 29 )
Municipio.create(nombre: " Zarzal ", departamento_id: 29 )

Municipio.create(nombre: " Carurú ", departamento_id: 30 )
Municipio.create(nombre: " Mitú ", departamento_id: 30 )
Municipio.create(nombre: " Taraira ", departamento_id: 30 )

Municipio.create(nombre: " Cumaribo ", departamento_id: 31 )
Municipio.create(nombre: " La Primavera ", departamento_id: 31 )
Municipio.create(nombre: " Puerto Carreño ", departamento_id: 31 )
Municipio.create(nombre: " Santa Rosalía ", departamento_id: 31 )



=begin
ubicacionviviendas


nivelacademicos
=end

ad = Tipouser.create(name: "Admin")
Tipouser.create(name: "Voluntario")
Tipouser.create(name: "ONG")


User.create(email: "ivantrips1@gmail.com",
            password: "123456",
            password_confirmation: "123456",
            esadmin: true,
            esong: false,
            esvoluntario:false,
            tipouser_id: ad.id,
            municipio_id: 1,
            aprobado: true
            )