# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)




Paise.create(bandera:"co", nombre:"Colombia")
Paise.create(bandera:"us", nombre:"United States")
Paise.create(bandera:"af", nombre:"Afghanistan")
Paise.create(bandera:"ax", nombre:"Aland Islands")
Paise.create(bandera:"al", nombre:"Albania")
Paise.create(bandera:"dz", nombre:"Algeria")
Paise.create(bandera:"as", nombre:"American Samoa")
Paise.create(bandera:"ad", nombre:"Andorra")
Paise.create(bandera:"ao", nombre:"Angola")
Paise.create(bandera:"ai", nombre:"Anguilla")
Paise.create(bandera:"ag", nombre:"Antigua")
Paise.create(bandera:"ar", nombre:"Argentina")
Paise.create(bandera:"am", nombre:"Armenia")
Paise.create(bandera:"aw", nombre:"Aruba")
Paise.create(bandera:"au", nombre:"Australia")
Paise.create(bandera:"at", nombre:"Austria")
Paise.create(bandera:"az", nombre:"Azerbaijan")
Paise.create(bandera:"bs", nombre:"Bahamas")
Paise.create(bandera:"bh", nombre:"Bahrain")
Paise.create(bandera:"bd", nombre:"Bangladesh")
Paise.create(bandera:"bb", nombre:"Barbados")
Paise.create(bandera:"by", nombre:"Belarus")
Paise.create(bandera:"be", nombre:"Belgium")
Paise.create(bandera:"bz", nombre:"Belize")
Paise.create(bandera:"bj", nombre:"Benin")
Paise.create(bandera:"bm", nombre:"Bermuda")
Paise.create(bandera:"bt", nombre:"Bhutan")
Paise.create(bandera:"bo", nombre:"Bolivia")
Paise.create(bandera:"ba", nombre:"Bosnia")
Paise.create(bandera:"bw", nombre:"Botswana")
Paise.create(bandera:"bv", nombre:"Bouvet Island")
Paise.create(bandera:"br", nombre:"Brazil")
Paise.create(bandera:"vg", nombre:"British Virgin Islands")
Paise.create(bandera:"bn", nombre:"Brunei")
Paise.create(bandera:"bg", nombre:"Bulgaria")
Paise.create(bandera:"bf", nombre:"Burkina Faso")
Paise.create(bandera:"ar", nombre:"Burma")
Paise.create(bandera:"bi", nombre:"Burundi")
Paise.create(bandera:"tc", nombre:"Caicos Islands")
Paise.create(bandera:"kh", nombre:"Cambodia")
Paise.create(bandera:"cm", nombre:"Cameroon")
Paise.create(bandera:"ca", nombre:"Canada")
Paise.create(bandera:"cv", nombre:"Cape Verde")
Paise.create(bandera:"ky", nombre:"Cayman Islands")
Paise.create(bandera:"cf", nombre:"Central African Republic")
Paise.create(bandera:"td", nombre:"Chad")
Paise.create(bandera:"cl", nombre:"Chile")
Paise.create(bandera:"cn", nombre:"China")
Paise.create(bandera:"cx", nombre:"Christmas Island")
Paise.create(bandera:"cc", nombre:"Cocos Islands")
Paise.create(bandera:"km", nombre:"Comoros")
Paise.create(bandera:"cg", nombre:"Congo Brazzaville")
Paise.create(bandera:"cd", nombre:"Congo")
Paise.create(bandera:"ck", nombre:"Cook Islands")
Paise.create(bandera:"cr", nombre:"Costa Rica")
Paise.create(bandera:"ci", nombre:"Cote Divoire")
Paise.create(bandera:"hr", nombre:"Croatia")
Paise.create(bandera:"cu", nombre:"Cuba")
Paise.create(bandera:"cy", nombre:"Cyprus")
Paise.create(bandera:"cz", nombre:"Czech Republic")
Paise.create(bandera:"dk", nombre:"Denmark")
Paise.create(bandera:"dj", nombre:"Djibouti")
Paise.create(bandera:"dm", nombre:"Dominica")
Paise.create(bandera:"do", nombre:"Dominican Republic")
Paise.create(bandera:"ec", nombre:"Ecuador")
Paise.create(bandera:"eg", nombre:"Egypt")
Paise.create(bandera:"sv", nombre:"El Salvador")
Paise.create(bandera:"gb", nombre:"England")
Paise.create(bandera:"gq", nombre:"Equatorial Guinea")
Paise.create(bandera:"er", nombre:"Eritrea")
Paise.create(bandera:"ee", nombre:"Estonia")
Paise.create(bandera:"et", nombre:"Ethiopia")
Paise.create(bandera:"eu", nombre:"European Union")
Paise.create(bandera:"fk", nombre:"Falkland Islands")
Paise.create(bandera:"fo", nombre:"Faroe Islands")
Paise.create(bandera:"fj", nombre:"Fiji")
Paise.create(bandera:"fi", nombre:"Finland")
Paise.create(bandera:"fr", nombre:"France")
Paise.create(bandera:"gf", nombre:"French Guiana")
Paise.create(bandera:"pf", nombre:"French Polynesia")
Paise.create(bandera:"tf", nombre:"French Territories")
Paise.create(bandera:"ga", nombre:"Gabon")
Paise.create(bandera:"gm", nombre:"Gambia")
Paise.create(bandera:"ge", nombre:"Georgia")
Paise.create(bandera:"de", nombre:"Germany")
Paise.create(bandera:"gh", nombre:"Ghana")
Paise.create(bandera:"gi", nombre:"Gibraltar")
Paise.create(bandera:"gr", nombre:"Greece")
Paise.create(bandera:"gl", nombre:"Greenland")
Paise.create(bandera:"gd", nombre:"Grenada")
Paise.create(bandera:"gp", nombre:"Guadeloupe")
Paise.create(bandera:"gu", nombre:"Guam")
Paise.create(bandera:"gt", nombre:"Guatemala")
Paise.create(bandera:"gw", nombre:"Guinea-Bissau")
Paise.create(bandera:"gn", nombre:"Guinea")
Paise.create(bandera:"gy", nombre:"Guyana")
Paise.create(bandera:"ht", nombre:"Haiti")
Paise.create(bandera:"hm", nombre:"Heard Island")
Paise.create(bandera:"hn", nombre:"Honduras")
Paise.create(bandera:"hk", nombre:"Hong Kong")
Paise.create(bandera:"hu", nombre:"Hungary")
Paise.create(bandera:"is", nombre:"Iceland")
Paise.create(bandera:"in", nombre:"India")
Paise.create(bandera:"io", nombre:"Indian Ocean Territory")
Paise.create(bandera:"id", nombre:"Indonesia")
Paise.create(bandera:"ir", nombre:"Iran")
Paise.create(bandera:"iq", nombre:"Iraq")
Paise.create(bandera:"ie", nombre:"Ireland")
Paise.create(bandera:"il", nombre:"Israel")
Paise.create(bandera:"it", nombre:"Italy")
Paise.create(bandera:"jm", nombre:"Jamaica")
Paise.create(bandera:"jp", nombre:"Japan")
Paise.create(bandera:"jo", nombre:"Jordan")
Paise.create(bandera:"kz", nombre:"Kazakhstan")
Paise.create(bandera:"ke", nombre:"Kenya")
Paise.create(bandera:"ki", nombre:"Kiribati")
Paise.create(bandera:"kw", nombre:"Kuwait")
Paise.create(bandera:"kg", nombre:"Kyrgyzstan")
Paise.create(bandera:"la", nombre:"Laos")
Paise.create(bandera:"lv", nombre:"Latvia")
Paise.create(bandera:"lb", nombre:"Lebanon")
Paise.create(bandera:"ls", nombre:"Lesotho")
Paise.create(bandera:"lr", nombre:"Liberia")
Paise.create(bandera:"ly", nombre:"Libya")
Paise.create(bandera:"li", nombre:"Liechtenstein")
Paise.create(bandera:"lt", nombre:"Lithuania")
Paise.create(bandera:"lu", nombre:"Luxembourg")
Paise.create(bandera:"mo", nombre:"Macau")
Paise.create(bandera:"mk", nombre:"Macedonia")
Paise.create(bandera:"mg", nombre:"Madagascar")
Paise.create(bandera:"mw", nombre:"Malawi")
Paise.create(bandera:"my", nombre:"Malaysia")
Paise.create(bandera:"mv", nombre:"Maldives")
Paise.create(bandera:"ml", nombre:"Mali")
Paise.create(bandera:"mt", nombre:"Malta")
Paise.create(bandera:"mh", nombre:"Marshall Islands")
Paise.create(bandera:"mq", nombre:"Martinique")
Paise.create(bandera:"mr", nombre:"Mauritania")
Paise.create(bandera:"mu", nombre:"Mauritius")
Paise.create(bandera:"yt", nombre:"Mayotte")
Paise.create(bandera:"mx", nombre:"Mexico")
Paise.create(bandera:"fm", nombre:"Micronesia")
Paise.create(bandera:"md", nombre:"Moldova")
Paise.create(bandera:"mc", nombre:"Monaco")
Paise.create(bandera:"mn", nombre:"Mongolia")
Paise.create(bandera:"me", nombre:"Montenegro")
Paise.create(bandera:"ms", nombre:"Montserrat")
Paise.create(bandera:"ma", nombre:"Morocco")
Paise.create(bandera:"mz", nombre:"Mozambique")
Paise.create(bandera:"na", nombre:"Namibia")
Paise.create(bandera:"nr", nombre:"Nauru")
Paise.create(bandera:"np", nombre:"Nepal")
Paise.create(bandera:"an", nombre:"Netherlands Antilles")
Paise.create(bandera:"nl", nombre:"Netherlands")
Paise.create(bandera:"nc", nombre:"New Caledonia")
Paise.create(bandera:"pg", nombre:"New Guinea")
Paise.create(bandera:"nz", nombre:"New Zealand")
Paise.create(bandera:"ni", nombre:"Nicaragua")
Paise.create(bandera:"ne", nombre:"Niger")
Paise.create(bandera:"ng", nombre:"Nigeria")
Paise.create(bandera:"nu", nombre:"Niue")
Paise.create(bandera:"nf", nombre:"Norfolk Island")
Paise.create(bandera:"kp", nombre:"North Korea")
Paise.create(bandera:"mp", nombre:"Northern Mariana Islands")
Paise.create(bandera:"no", nombre:"Norway")
Paise.create(bandera:"om", nombre:"Oman")
Paise.create(bandera:"pk", nombre:"Pakistan")
Paise.create(bandera:"pw", nombre:"Palau")
Paise.create(bandera:"ps", nombre:"Palestine")
Paise.create(bandera:"pa", nombre:"Panama")
Paise.create(bandera:"py", nombre:"Paraguay")
Paise.create(bandera:"pe", nombre:"Peru")
Paise.create(bandera:"ph", nombre:"Philippines")
Paise.create(bandera:"pn", nombre:"Pitcairn Islands")
Paise.create(bandera:"pl", nombre:"Poland")
Paise.create(bandera:"pt", nombre:"Portugal")
Paise.create(bandera:"pr", nombre:"Puerto Rico")
Paise.create(bandera:"qa", nombre:"Qatar")
Paise.create(bandera:"re", nombre:"Reunion")
Paise.create(bandera:"ro", nombre:"Romania")
Paise.create(bandera:"ru", nombre:"Russia")
Paise.create(bandera:"rw", nombre:"Rwanda")
Paise.create(bandera:"sh", nombre:"Saint Helena")
Paise.create(bandera:"kn", nombre:"Saint Kitts and Nevis")
Paise.create(bandera:"lc", nombre:"Saint Lucia")
Paise.create(bandera:"pm", nombre:"Saint Pierre")
Paise.create(bandera:"vc", nombre:"Saint Vincent")
Paise.create(bandera:"ws", nombre:"Samoa")
Paise.create(bandera:"sm", nombre:"San Marino")
Paise.create(bandera:"gs", nombre:"Sandwich Islands")
Paise.create(bandera:"st", nombre:"Sao Tome")
Paise.create(bandera:"sa", nombre:"Saudi Arabia")
Paise.create(bandera:"sn", nombre:"Senegal")
Paise.create(bandera:"cs", nombre:"Serbia")
Paise.create(bandera:"rs", nombre:"Serbia")
Paise.create(bandera:"sc", nombre:"Seychelles")
Paise.create(bandera:"sl", nombre:"Sierra Leone")
Paise.create(bandera:"sg", nombre:"Singapore")
Paise.create(bandera:"sk", nombre:"Slovakia")
Paise.create(bandera:"si", nombre:"Slovenia")
Paise.create(bandera:"sb", nombre:"Solomon Islands")
Paise.create(bandera:"so", nombre:"Somalia")
Paise.create(bandera:"za", nombre:"South Africa")
Paise.create(bandera:"kr", nombre:"South Korea")
Paise.create(bandera:"es", nombre:"Spain")
Paise.create(bandera:"lk", nombre:"Sri Lanka")
Paise.create(bandera:"sd", nombre:"Sudan")
Paise.create(bandera:"sr", nombre:"Suriname")
Paise.create(bandera:"sj", nombre:"Svalbard")
Paise.create(bandera:"sz", nombre:"Swaziland")
Paise.create(bandera:"se", nombre:"Sweden")
Paise.create(bandera:"ch", nombre:"Switzerland")
Paise.create(bandera:"sy", nombre:"Syria")
Paise.create(bandera:"tw", nombre:"Taiwan")
Paise.create(bandera:"tj", nombre:"Tajikistan")
Paise.create(bandera:"tz", nombre:"Tanzania")
Paise.create(bandera:"th", nombre:"Thailand")
Paise.create(bandera:"tl", nombre:"Timorleste")
Paise.create(bandera:"tg", nombre:"Togo")
Paise.create(bandera:"tk", nombre:"Tokelau")
Paise.create(bandera:"to", nombre:"Tonga")
Paise.create(bandera:"tt", nombre:"Trinidad")
Paise.create(bandera:"tn", nombre:"Tunisia")
Paise.create(bandera:"tr", nombre:"Turkey")
Paise.create(bandera:"tm", nombre:"Turkmenistan")
Paise.create(bandera:"tv", nombre:"Tuvalu")
Paise.create(bandera:"ug", nombre:"Uganda")
Paise.create(bandera:"ua", nombre:"Ukraine")
Paise.create(bandera:"ae", nombre:"United Arab Emirates")
Paise.create(bandera:"uy", nombre:"Uruguay")
Paise.create(bandera:"um", nombre:"Us Minor Islands")
Paise.create(bandera:"vi", nombre:"Us Virgin Islands")
Paise.create(bandera:"uz", nombre:"Uzbekistan")
Paise.create(bandera:"vu", nombre:"Vanuatu")
Paise.create(bandera:"va", nombre:"Vatican City")
Paise.create(bandera:"ve", nombre:"Venezuela")
Paise.create(bandera:"vn", nombre:"Vietnam")
Paise.create(bandera:"wf", nombre:"Wallis and Futuna")
Paise.create(bandera:"eh", nombre:"Western Sahara")
Paise.create(bandera:"ye", nombre:"Yemen")
Paise.create(bandera:"zm", nombre:"Zambia")
Paise.create(bandera:"zw", nombre:"Zimbabwe")


TipoDeSexo.create( nombre: "Masculino")
TipoDeSexo.create( nombre: "Femenino")

TipoEstadoCivil.create(nombre:"Soltero")
TipoEstadoCivil.create(nombre:"Casado")
TipoEstadoCivil.create(nombre:"Viudo")
TipoEstadoCivil.create(nombre:"Separado")

TipoDocumento.create(nombre: "C.C.")
TipoDocumento.create(nombre: "C.E.")


Religion.create(nombre: "Cristiano")
Religion.create(nombre: "Judio")
Religion.create(nombre: "Evangelico")
Religion.create(nombre: "Catolico")
Religion.create(nombre: "Otro")


Tenenciavivienda.create(nombre: "Propia")
Tenenciavivienda.create(nombre: "Alquilada")
Tenenciavivienda.create(nombre: "Familiar")
Tenenciavivienda.create(nombre: "Albergue")

Tipocontacto.create(nombre:"Casa")
Tipocontacto.create(nombre:"Movil")
Tipocontacto.create(nombre:"Trabajo")

Ubicacionvivienda.create(nombre:"Area Urbana")
h = Ubicacionvivienda.create(nombre:"Area Rural")

Detalleubicacion.create(nombre:"Disperso", ubicacionvivienda:h)
Detalleubicacion.create(nombre:"Centro Poblado", ubicacionvivienda:h)


Tipoestudio.create(nombre:"Sin escolaridad")
Tipoestudio.create(nombre:"Primaria Incompleta")
Tipoestudio.create(nombre:"Primaria Completa")
Tipoestudio.create(nombre:"Secundaria Incompleta")
Tipoestudio.create(nombre:"Secundaria Completa")
Tipoestudio.create(nombre:"Tecnico Incompleta")
Tipoestudio.create(nombre:"Tecnico Completa")
Tipoestudio.create(nombre:"Tecnologo Incompleta")
Tipoestudio.create(nombre:"Tecnologo Completa")
Tipoestudio.create(nombre:"Pregrado Incompleta")
Tipoestudio.create(nombre:"Pregrado Completa")
Tipoestudio.create(nombre:"Especializacion Incompleta")
Tipoestudio.create(nombre:"Especializacion Completa")
Tipoestudio.create(nombre:"Maestria Incompleta")
Tipoestudio.create(nombre:"Maestria Completa")
Tipoestudio.create(nombre:"Doctorado Incompleta")
Tipoestudio.create(nombre:"Doctorado Completa")


Jornadaestudio.create(nombre:"Distancia")
Jornadaestudio.create(nombre:"Presencial")
Jornadaestudio.create(nombre:"Semipresencial")
Jornadaestudio.create(nombre:"Virtual")

Aptitude.create(id: 1,nombre:"Responsabilidad")
Aptitude.create(id: 2,nombre:"Liderazgo")

PruebasCompetencia.create(id: 1,aptitudes_id: 1, nombre:"Prueba de Responsabilidad")
PruebasCompetencia.create(id: 2,aptitudes_id: 2,nombre: "Prueba de Liderazgo")

Pregunta.create(id:1,pruebas_competencia_id: 1,nombre:"PARTIENDO DE EXPERIENCIAS PASADAS, USTED SE CARACTERIZA POR:")

OpcionesRespuestum.create(pregunta_id:1,valor: 1,nombre:"Cumple con las políticas organizacionales en materia de responsabilidad social, solo cuando se le solicita")
OpcionesRespuestum.create(pregunta_id:1,valor: 2,nombre:"se identifica con las políticas sociales en materias de responsabilidad social")
OpcionesRespuestum.create(pregunta_id:1,valor: 3,nombre:"Promueve las políticas organizacionales en materia de responsabilidad social.")
OpcionesRespuestum.create(pregunta_id:1,valor: 4,nombre:"Fija políticas organizacionales en materia de responsabilidad social, con visión de largo plazo.")
OpcionesRespuestum.create(pregunta_id:1,valor: 5,nombre:"Se identifica con las políticas organizacionales en materia de responsabilidad social, y motiva a los colaboradores y/o pares de su área a actuar de la misma manera.")

Pregunta.create(id:2,pruebas_competencia_id: 1,nombre:"LO QUE HACE DIFERENTES SUS ACCIONES A LA DEL RESTO DE SUS COMPAÑEROS ES PORQUE:")

OpcionesRespuestum.create(pregunta_id:2,valor: 1,nombre:"No propone acciones orientadas a colaborar con la sociedad")
OpcionesRespuestum.create(pregunta_id:2,valor: 2,nombre:"Lleva a cabo acciones orientadas a colaborar con la sociedad en todo aquello que guarde relación con sus propias tareas o responsabilidades.")
OpcionesRespuestum.create(pregunta_id:2,valor: 3,nombre:"Propone acciones orientadas a colaborar con la sociedad en las áreas donde ésta presenta mayores carencias.")
OpcionesRespuestum.create(pregunta_id:2,valor: 4,nombre:"Diseña, propone y lleva a cabo junto con su área de trabajo, propuestas orientadas a contribuir y colaborar con la sociedad en las áreas donde esta presenta mayores carencias")
OpcionesRespuestum.create(pregunta_id:2,valor: 5,nombre:"Diseña, propone y luego lleva a cabo propuestas orientadas a contribuir y colaborar con la sociedad en las áreas en las cuales esta presenta mayores carencias, y por ende, mayor necesidad de ayuda y colaboración")


Pregunta.create(id:3,pruebas_competencia_id: 1,nombre:"FRENTE A SITUACIONES QUE NO CORRESPONDEN A SU ACTUAR COTIDIANO USTED:")

OpcionesRespuestum.create(pregunta_id:3,valor: 1,nombre:"Le cuesta comprender otras culturas y adaptarse a ellas, por lo que no logra realizar un aporte significativo a las políticas organizacionales en materia de responsabilidad social.")
OpcionesRespuestum.create(pregunta_id:3,valor: 2,nombre:"Comprende rápidamente otras culturas")
OpcionesRespuestum.create(pregunta_id:3,valor: 3,nombre:"Comprende otras culturas y utiliza dicha comprensión en beneficio de las políticas organizacionales en materia de responsabilidad social.")
OpcionesRespuestum.create(pregunta_id:3,valor: 4,nombre:"Comprende otras culturas, sus maneras de pensar y comportarse y utiliza dicha comprensión en beneficio de las políticas organizacionales en materia de responsabilidad social")
OpcionesRespuestum.create(pregunta_id:3,valor: 5,nombre:"Comprende rápidamente otras culturas, sus maneras de pensar y comportarse en las diferentes formas de hacer las cosas, y utiliza dicha comprensión en beneficio de las políticas organizacionales en materia de responsabilidad social.")

Pregunta.create(id:4,pruebas_competencia_id: 1,nombre:"¿SE HA VISTO EXPUESTO A ALGUNA DE LAS SIGUIENTES SITUACIONES?")


OpcionesRespuestum.create(pregunta_id:4,valor: 1,nombre:"No se involucra en la implementación de los planes de asistencia y ayuda social que la organización realiza, por considerar que sus responsabilidades y obligaciones laborales requiere de su dedicación absoluta o porque piensa que hacerlo no corresponde a su rol")
OpcionesRespuestum.create(pregunta_id:4,valor: 2,nombre:"Promociona de manera formal e informal, los programas de asistencia con los que cuenta la organización, a fin de que lleguen quienes los necesitan")
OpcionesRespuestum.create(pregunta_id:4,valor: 3,nombre:"Desarrolla y participa activamente en la implementación de planes orientados a fomentar el bien común")
OpcionesRespuestum.create(pregunta_id:4,valor: 4,nombre:"Colabora en la implementación de los planes de asistencia y ayuda social que lleva adelante la organización.")
OpcionesRespuestum.create(pregunta_id:4,valor: 5,nombre:"Participa e interviene en el desarrollo y ejecución de los planes de asistencia que instrumenta su organización, y fomenta igual actitud entre sus colaboradores.")

Pregunta.create(id:5,pruebas_competencia_id: 1,nombre:"DENTRO DE LOS EQUIPOS DE TRABAJO A LOS QUE HA HECHO PARTE, USTED SE DISTINGUE POR:")
OpcionesRespuestum.create(pregunta_id:5,valor: 1,nombre:"No comprende el porqué de las políticas organizacionales en materia de responsabilidad social; considera que la asistencia y ayuda en los temas sociales es responsabilidad exclusiva de los organismos del sector público")
OpcionesRespuestum.create(pregunta_id:5,valor: 2,nombre:"Es un referente para sus compañeros en materia de responsabilidad social")
OpcionesRespuestum.create(pregunta_id:5,valor: 3,nombre:"Es un refrene para sus colaboradores y en el ámbito del área en dónde se desempeña en materia de responsabilidad social")
OpcionesRespuestum.create(pregunta_id:5,valor: 4,nombre:"Es un referente de su área y en el ámbito de la organización en materia de responsabilidad social.")
OpcionesRespuestum.create(pregunta_id:5,valor: 5,nombre:"Es un referente en la organización y en el mercado donde actúa en materia de responsabilidad social.")












Pregunta.create(id:6,pruebas_competencia_id: 2,nombre:"¿HA SIDO RECONOCIDO POR ALGUNOS DE LOS SIGUIENTES COMPORTAMIENTOS?")

OpcionesRespuestum.create(pregunta_id:6,valor: 1,nombre:"no logra asegurar una adecuada conducción de personas ni desarrollar su talento")
OpcionesRespuestum.create(pregunta_id:6,valor: 2,nombre:"Asegura una adecuada conducción de personas y el desarrollo de su talento")
OpcionesRespuestum.create(pregunta_id:6,valor: 3,nombre:"Busca siempre asegurar una adecuada conducción de personas y el desarrollo de su talento y propone nuevas estrategias para ello cuando lo considera oportuno")
OpcionesRespuestum.create(pregunta_id:6,valor: 4,nombre:"Propone y diseña proceso y cursos de acción y métodos de trabajo con el propósito de asegurar una adecuada conducción de personas y desarrollar su talento.")
OpcionesRespuestum.create(pregunta_id:6,valor: 5,nombre:"Diseña estrategias, procesos, cursos de acción y métodos de trabajo con el propósito de asegurar una exitosa conducción de personas y desarrollar su talento.")

Pregunta.create(id:7,pruebas_competencia_id: 2,nombre:"EN SU DIARIO VIVIR, USTED SUELE:")
OpcionesRespuestum.create(pregunta_id:7,valor: 1,nombre:"No es eficaz para obtener el compromiso y el respalda de sus superiores a fin de enfrentar los desafíos del equipo que integra los equipos a su cargo.")
OpcionesRespuestum.create(pregunta_id:7,valor: 2,nombre:"tiene el compromiso y respaldo de sus superiores para el logro de los desafíos del equipo que integra")
OpcionesRespuestum.create(pregunta_id:7,valor: 3,nombre:"Propone cursos de acción con el fin de lograr el compromiso y respaldo de sus superiores para enfrentar los desafíos a su cargo.")
OpcionesRespuestum.create(pregunta_id:7,valor: 4,nombre:"Delinea estrategias y cursos de acción con el fin de lograr el compromiso y el respaldo de las distintas áreas de la organización para alcanzar la estrategia.")
OpcionesRespuestum.create(pregunta_id:7,valor: 5,nombre:"Propone y diseña procesos y cursos de acción con el fin de lograr el compromiso y respaldo de sus superiores para enfrentar los desafíos propuestas para su área.")

Pregunta.create(id:8,pruebas_competencia_id: 2,nombre:"DENTRO DE LOS EQUIPOS DE TRABAJO A LOS QUE HA PERTENECIDO USTED SE HA DISTIGUIDO PORQUE:")
OpcionesRespuestum.create(pregunta_id:8,valor: 1,nombre:"genera un clima organizacional tenso")
OpcionesRespuestum.create(pregunta_id:8,valor: 2,nombre:"Propicia un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:8,valor: 3,nombre:"Contribuye a mantener un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:8,valor: 4,nombre:"Genera y mantiene un modo activo, un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:8,valor: 5,nombre:"promueve y sostiene un clima organizacional armónico y desafiante ")

Pregunta.create(id:9,pruebas_competencia_id: 2,nombre:"LA GENTE QUE LO CONOCE PODRÍA DECIR DE USTED QUE:")
OpcionesRespuestum.create(pregunta_id:9,valor: 1,nombre:"No es vista por su entorno organizacional como un ejemplo a seguir por su capacidad de liderar y lograr un desarrollar de sus colaboradores ")
OpcionesRespuestum.create(pregunta_id:9,valor: 2,nombre:"Propicia un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:9,valor: 3,nombre:"Contribuye a mantener un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:9,valor: 4,nombre:"Genera y mantiene un modo activo, un clima organizacional armónico y desafiante")
OpcionesRespuestum.create(pregunta_id:9,valor: 5,nombre:"promueve y sostiene un clima organizacional armónico y desafiante ")

Pregunta.create(id:10,pruebas_competencia_id: 2,nombre:"¿CUAL DE LOS SIGUIENTES POSTULADOS LO DEFINEN DE MEJOR MANERA?")
OpcionesRespuestum.create(pregunta_id:10,valor: 1,nombre:"Carece de visión y proyección a futuro para la conducción y desarrollo de personas ")
OpcionesRespuestum.create(pregunta_id:10,valor: 2,nombre:"Muestra visión y proyección, en el corto plazo, para la conducción y desarrollo de personas")
OpcionesRespuestum.create(pregunta_id:10,valor: 3,nombre:"Considera la necesidad de pensar a futuro en la conducción y desarrollo de personas ")
OpcionesRespuestum.create(pregunta_id:10,valor: 4,nombre:"su desempeño en la conducción y desarrollo de personas transluce visión y proyección en el mediano plazo")
OpcionesRespuestum.create(pregunta_id:10,valor: 5,nombre:"Evidencia visión y proyección de largo plazo en la conducción y desarrollo de personas")

=begin
ubicacionviviendas


nivelacademicos
=end